use super::super::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/v1/works",
            get(crate::server::work_handlers::get_works_handler)
                .post(crate::server::work_handlers::post_work_handler),
        )
        .route(
            "/v1/works/session-bindings/{session_id}",
            get(crate::server::work_handlers::get_work_session_binding_handler)
                .post(crate::server::work_handlers::post_work_session_binding_handler),
        )
        .route(
            "/v1/works/{work_id}",
            get(crate::server::work_handlers::get_work_handler),
        )
        .route(
            "/v1/works/{work_id}/actions",
            post(crate::server::work_handlers::post_work_action_handler),
        )
        .route(
            "/v1/works/{work_id}/branches",
            get(crate::server::work_handlers::get_work_branches_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/archived",
            get(crate::server::work_handlers::get_archived_work_branches_handler),
        )
        .route(
            "/v1/works/{work_id}/branch-comparisons",
            post(crate::server::work_handlers::post_work_branch_comparison_handler),
        )
        .route(
            "/v1/works/{work_id}/read-cursor",
            axum::routing::put(crate::server::work_handlers::put_work_read_cursor_handler),
        )
        .route(
            "/v1/works/{work_id}/events",
            get(crate::server::work_handlers::get_work_events_handler),
        )
        .route(
            "/v1/works/{work_id}/criteria",
            get(crate::server::work_handlers::get_work_criteria_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/turns",
            post(crate::server::work_handlers::post_work_branch_turn_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/actions",
            post(crate::server::work_handlers::post_work_branch_action_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/deletion-operations",
            post(crate::server::work_handlers::post_work_branch_deletion_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/deletion-operations/{operation_id}",
            get(crate::server::work_handlers::get_work_branch_deletion_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/patch-artifacts",
            get(crate::server::work_handlers::get_work_branch_patch_artifacts_handler)
                .post(crate::server::work_handlers::post_work_branch_patch_artifact_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/patch-artifacts/{patch_artifact_id}",
            get(crate::server::work_handlers::get_work_branch_patch_artifact_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/patch-artifacts/{patch_artifact_id}/content",
            get(crate::server::work_handlers::get_work_branch_patch_artifact_content_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/patch-materializations",
            get(crate::server::work_handlers::get_work_patch_materializations_handler)
                .post(crate::server::work_handlers::post_work_patch_materialization_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/patch-materializations/{operation_id}",
            get(crate::server::work_handlers::get_work_patch_materialization_handler)
                .delete(crate::server::work_handlers::delete_work_patch_materialization_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/patch-commits",
            get(crate::server::work_handlers::get_work_patch_commits_handler)
                .post(crate::server::work_handlers::post_work_patch_commit_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/patch-commits/{operation_id}",
            get(crate::server::work_handlers::get_work_patch_commit_handler)
                .delete(crate::server::work_handlers::delete_work_patch_commit_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/transcript",
            get(crate::server::work_handlers::get_work_branch_transcript_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/attachments",
            post(crate::server::work_handlers::post_work_branch_attachment_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/attachments/{attachment_id}",
            axum::routing::delete(
                crate::server::work_handlers::delete_work_branch_attachment_handler,
            ),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/control-operations",
            post(crate::server::work_handlers::post_work_branch_control_operation_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/control-operations/{operation_id}",
            get(crate::server::work_handlers::get_work_branch_control_operation_handler)
                .delete(crate::server::work_handlers::delete_work_branch_control_operation_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/forks",
            post(crate::server::work_handlers::post_work_branch_fork_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/forks/{operation_id}",
            get(crate::server::work_handlers::get_work_branch_fork_handler)
                .delete(crate::server::work_handlers::delete_work_branch_fork_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/task-graph",
            get(crate::server::work_handlers::get_work_task_graph_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/criteria-proposals",
            get(crate::server::work_handlers::list_work_criteria_proposals_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/criteria-proposals/{proposal_id}",
            get(crate::server::work_handlers::get_work_criteria_proposal_handler),
        )
        .route(
            "/v1/works/{work_id}/branches/{branch_id}/criteria-proposals/{proposal_id}/decision",
            axum::routing::put(
                crate::server::work_handlers::put_work_criteria_proposal_decision_handler,
            ),
        )
        .route(
            "/runs",
            get(crate::server::run::handlers::list_runs_handler),
        )
        .route(
            "/preferences",
            get(preferences_handlers::list_preferences_handler),
        )
        .route(
            "/preferences/{key}",
            axum::routing::put(preferences_handlers::put_preference_handler),
        )
        .route(
            "/resources/usage",
            get(resource_handlers::get_resource_usage_handler),
        )
        .route(
            "/resources/limits",
            get(resource_handlers::get_resource_limits_handler),
        )
}
