# The prebuilt image needs only the release binaries and their license. Docker
# automatically includes the Dockerfile and this ignore file in the context.
**
!LICENSE
!target/
!target/x86_64-unknown-linux-gnu/
!target/x86_64-unknown-linux-gnu/release/
!target/x86_64-unknown-linux-gnu/release/astra-server
!target/x86_64-unknown-linux-gnu/release/astra
