//! Dynamic bundled skills — prompt content generated by Rust functions.
//!
//! Each skill is a function returning (manifest_yaml, instructions) so that
//! tool names, paths, and other constants are compiled-in rather than
//! hardcoded strings that drift out of sync.

mod debug;
mod reflect;
mod remember;
mod review;
mod skillify;
mod stuck;
mod verify;

/// Returns all dynamic skill contents as `(frontmatter_yaml + body)` strings
/// ready to be parsed by `parse_skill_md`.
///
/// `batch` was deleted: its instructions told the model to call the
/// removed `delegate` action, and its triggers (`parallel`, `bulk`,
/// `for each`) auto-fired on read-only review requests. With
/// `agent.spawn` + `run_in_background: true` documented in the tool
/// description, the model already knows how to fan out parallel work.
pub fn all_dynamic_skills() -> Vec<String> {
    vec![
        debug::skill_content(),
        reflect::skill_content(),
        review::skill_content(),
        skillify::skill_content(),
        stuck::skill_content(),
        verify::skill_content(),
        remember::skill_content(),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn returns_seven_skills() {
        // Was 8 — `batch` removed (referenced removed `delegate` action,
        // and its triggers auto-fired on read-only review requests).
        assert_eq!(all_dynamic_skills().len(), 7);
    }

    /// Regression: the dynamic `batch` skill must NOT come back. It
    /// referenced the removed `delegate` action and matched on overly
    /// broad triggers like "parallel" / "bulk" / "for each", which
    /// caused it to auto-fire on read-only multi-angle review requests
    /// (session f3c4b457). Guarding against silent reintroduction.
    #[test]
    fn batch_dynamic_skill_is_not_reintroduced() {
        let all = all_dynamic_skills().join("\n");
        assert!(
            !all.contains("name: batch\n"),
            "the `batch` dynamic skill was deleted; do not reintroduce \
             without first proving it doesn't auto-fire on read-only \
             multi-angle review and that it does not reference removed \
             tool actions"
        );
    }

    #[test]
    fn all_start_with_frontmatter() {
        for (i, content) in all_dynamic_skills().into_iter().enumerate() {
            assert!(
                content.starts_with("---"),
                "skill {i} should start with YAML frontmatter"
            );
        }
    }

    #[test]
    fn all_contain_name_field() {
        for (i, content) in all_dynamic_skills().into_iter().enumerate() {
            assert!(
                content.contains("name:"),
                "skill {i} should contain name field"
            );
        }
    }

    #[test]
    fn no_empty_skills() {
        for content in all_dynamic_skills() {
            assert!(content.len() > 50, "skill content should be substantial");
        }
    }

    #[test]
    fn individual_skill_names_present() {
        let all = all_dynamic_skills().join("\n");
        for name in [
            "debug", "reflect", "review", "skillify", "stuck", "verify", "remember",
        ] {
            assert!(
                all.contains(&format!("name: {name}")),
                "missing skill: {name}"
            );
        }
    }
}
