use super::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/agents",
            post(agents::create_agent_handler).get(agents::list_agents_handler),
        )
        .route(
            "/agents/{agent_id}",
            get(agents::get_agent_handler)
                .put(agents::update_agent_handler)
                .delete(agents::delete_agent_handler),
        )
        .route(
            "/events",
            post(crate::service_handlers::events::create_event_handler)
                .get(crate::service_handlers::events::list_events_handler),
        )
        .route(
            "/sync/outbox/events",
            post(crate::service_handlers::events::create_sync_outbox_event_handler),
        )
        .route(
            "/events/{event_id}",
            get(crate::service_handlers::events::get_event_handler)
                .delete(crate::service_handlers::events::delete_event_handler),
        )
        .route(
            "/events/causal-chain/{causal_chain_id}",
            get(crate::service_handlers::events::get_causal_chain_handler),
        )
        .route(
            "/events/session/{session_id}",
            get(crate::service_handlers::events::get_session_events_handler),
        )
        .route(
            "/context",
            post(context::create_snapshot_handler).get(context::list_snapshots_handler),
        )
        .route(
            "/context/{context_capture_id}",
            get(context::get_snapshot_handler),
        )
        .route(
            "/decisions",
            post(crate::service_handlers::decisions::record_decision_handler)
                .get(crate::service_handlers::decisions::list_decisions_handler),
        )
        .route(
            "/decisions/{decision_id}",
            get(crate::service_handlers::decisions::get_decision_handler),
        )
        .route(
            "/decisions/{decision_id}/audit",
            get(crate::service_handlers::decisions::audit_decision_handler),
        )
        .route(
            "/triggers",
            post(crate::service_handlers::triggers::create_trigger_handler)
                .get(crate::service_handlers::triggers::list_triggers_handler),
        )
        .route(
            "/triggers/{trigger_id}",
            delete(crate::service_handlers::triggers::delete_trigger_handler),
        )
        .route(
            "/triggers/{trigger_id}/fire",
            post(crate::service_handlers::triggers::fire_webhook_handler),
        )
        .route(
            "/workflows",
            get(crate::service_handlers::workflows::list_workflows_handler),
        )
        .route(
            "/sandbox",
            post(crate::service_handlers::sandbox::create_sandbox_handler)
                .get(crate::service_handlers::sandbox::list_sandboxes_handler),
        )
        .route(
            "/sandbox/{name}",
            get(crate::service_handlers::sandbox::get_sandbox_handler)
                .delete(crate::service_handlers::sandbox::delete_sandbox_handler),
        )
        .route(
            "/branches",
            post(crate::service_handlers::branches::create_branch_handler)
                .delete(crate::service_handlers::branches::delete_branch_handler),
        )
        .route(
            "/branches/diff",
            post(crate::service_handlers::branches::diff_branch_handler),
        )
        .route(
            "/branches/merge",
            post(crate::service_handlers::branches::merge_branch_handler),
        )
        .route(
            "/branches/cost-estimate",
            post(crate::service_handlers::branches::estimate_cost_handler),
        )
        .route(
            "/data-versioning/checkpoints",
            post(data_layer::versioning::create_checkpoint_handler)
                .get(data_layer::versioning::list_checkpoints_handler),
        )
        .route(
            "/data-versioning/checkpoints/{name}/events",
            get(data_layer::versioning::get_events_at_checkpoint_handler),
        )
        .route(
            "/data-versioning/lineage/{event_id}/chain",
            get(data_layer::versioning::get_causal_chain_handler),
        )
        .route(
            "/data-versioning/lineage/{event_id}/upstream",
            get(data_layer::versioning::trace_upstream_handler),
        )
        .route(
            "/data-versioning/sandbox/{name}/checkpoint",
            post(data_layer::versioning::sandbox_checkpoint_handler),
        )
        .route(
            "/data-versioning/sandbox/{name}/restore",
            post(data_layer::versioning::sandbox_restore_handler),
        )
}
