use super::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/model-access",
            get(data_layer::models::get_model_access_handler),
        )
        .route(
            "/models",
            post(data_layer::models::create_model_handler)
                .get(data_layer::models::list_models_handler),
        )
        .route(
            "/models/memory",
            get(data_layer::models::get_memory_model_handler),
        )
        .route(
            "/models/{model_name}",
            get(data_layer::models::get_model_handler)
                .put(data_layer::models::update_model_handler)
                .delete(data_layer::models::delete_model_handler),
        )
        .route(
            "/models/{model_name}/check",
            post(data_layer::models::check_model_handler),
        )
        .route("/skills", get(skills::list_skills_handler))
        .route("/skills/status", get(skills::get_skill_status_handler))
        .route("/skills/publish", post(skills::publish_skill_handler))
        .route(
            "/skills/user",
            get(user_skill_handlers::list_user_skills_handler)
                .post(user_skill_handlers::create_user_skill_handler),
        )
        .route(
            "/skills/user/{skill_name}/versions",
            get(user_skill_handlers::list_user_skill_versions_handler)
                .post(user_skill_handlers::submit_user_skill_version_handler),
        )
        .route(
            "/skills/user/{skill_name}/evaluations",
            post(user_skill_handlers::record_user_skill_evaluation_handler),
        )
        .route(
            "/skills/user/{skill_name}/activate",
            post(user_skill_handlers::activate_user_skill_handler),
        )
        .route(
            "/skills/{skill_name}/info",
            get(skills::get_skill_info_handler),
        )
        .route("/skills/{skill_id}", get(skills::get_skill_handler))
        .route(
            "/skills/{skill_id}/versions",
            get(skills::list_skill_versions_handler),
        )
        .route(
            "/skills/{skill_name}/unpublish",
            post(skills::unpublish_skill_handler),
        )
        .route(
            "/skills/{skill_name}/config/validate",
            get(config_admin::skill::validate_config_handler),
        )
        .route(
            "/skills/{skill_name}/config",
            get(config_admin::skill::get_effective_config_handler),
        )
        .route(
            "/skills/{skill_name}/config/{setting_name}",
            axum::routing::put(config_admin::skill::set_setting_handler)
                .delete(config_admin::skill::delete_setting_handler),
        )
        .route(
            "/skills/{skill_name}/resources",
            get(config_admin::skill::list_resources_handler),
        )
        .route(
            "/skills/{skill_name}/resources/{resource_key}",
            axum::routing::put(config_admin::skill::bind_resource_handler)
                .delete(config_admin::skill::unbind_resource_handler),
        )
        .route(
            "/marketplace/install",
            post(crate::service_handlers::marketplace::install_skill_handler),
        )
        .route(
            "/marketplace/uninstall",
            post(crate::service_handlers::marketplace::uninstall_skill_handler),
        )
        .route(
            "/marketplace/upgrade",
            post(crate::service_handlers::marketplace::upgrade_skill_handler),
        )
        .route(
            "/marketplace/rollback",
            post(crate::service_handlers::marketplace::rollback_skill_handler),
        )
        .route(
            "/marketplace/installed",
            get(crate::service_handlers::marketplace::list_installed_handler),
        )
        .route(
            "/marketplace/credentials",
            post(crate::service_handlers::marketplace::save_credential_handler)
                .delete(crate::service_handlers::marketplace::delete_credential_handler),
        )
        .route(
            "/marketplace/quality-report",
            post(crate::service_handlers::marketplace::submit_quality_report_handler),
        )
        .route(
            "/marketplace/stats/{skill_name}",
            get(crate::service_handlers::marketplace::get_skill_stats_handler),
        )
        .route(
            "/marketplace/search",
            get(crate::service_handlers::marketplace::search_marketplace_handler),
        )
}
