use super::*;

pub(super) fn add_routes(router: Router<AppState>, state: AppState) -> Router<AppState> {
    router
        .route(
            "/sessions",
            post(session::session_handlers::create_session_handler)
                .get(session::session_handlers::list_sessions_handler),
        )
        .route(
            "/sessions/resumable",
            get(session::session_handlers::list_resumable_sessions_handler),
        )
        .route(
            "/sessions/{session_id}",
            get(session::session_handlers::get_session_handler)
                .put(session::session_handlers::update_session_handler)
                .delete(session::session_handlers::delete_session_handler),
        )
        .route(
            "/sessions/{session_id}/state",
            get(session::session_handlers::get_session_state_handler),
        )
        .route(
            "/sessions/{session_id}/runs",
            get(session::session_run_tree::get_session_run_tree_handler),
        )
        .route(
            "/sessions/{session_id}/transcript",
            get(session::session_handlers::get_session_transcript_handler),
        )
        .route(
            "/sessions/{session_id}/turns/{turn_id}/trace",
            get(session::session_trace::get_session_turn_trace_handler),
        )
        .route(
            "/sessions/{session_id}/devices",
            get(session::session_handlers::list_session_devices_handler),
        )
        .route(
            "/sessions/{session_id}/device/enroll",
            post(session::session_handlers::enroll_session_device_handler),
        )
        .route(
            "/sessions/{session_id}/device/challenge",
            post(session::session_handlers::create_session_device_challenge_handler),
        )
        .route(
            "/sessions/{session_id}/device/revoke",
            post(session::session_handlers::revoke_session_device_handler),
        )
        .route(
            "/sessions/{session_id}/device/trust",
            post(session::session_handlers::trust_session_device_handler),
        )
        .route(
            "/sessions/{session_id}/device/events",
            get(session::session_handlers::session_device_events_handler),
        )
        .route(
            "/sessions/{session_id}/close",
            post(session::session_handlers::close_session_handler),
        )
        .route(
            "/sessions/{session_id}/resume",
            post(session::session_handlers::resume_session_handler),
        )
        .route(
            "/sessions/{session_id}/attachments",
            post(session::session_handlers::attach_session_handler),
        )
        .route(
            "/sessions/{session_id}/context/segments:batchGet",
            post(session::session_handlers::get_session_segments_handler),
        )
        .route(
            "/sessions/{session_id}/context/segments:upload",
            post(session::session_handlers::upload_session_segments_handler),
        )
        .route(
            "/sessions/{session_id}/publish",
            post(session::session_handlers::publish_session_handler),
        )
        .route(
            "/sessions/{session_id}/handoffs",
            post(session::session_handlers::request_session_handoff_handler),
        )
        .route(
            "/sessions/{session_id}/handoffs/{handoff_id}",
            get(session::session_handlers::get_session_handoff_handler),
        )
        .route(
            "/sessions/{session_id}/handoffs/{handoff_id}/transitions",
            post(session::session_handlers::transition_session_handoff_handler),
        )
        .route(
            "/sessions/{session_id}/handoffs/{handoff_id}/fence",
            post(session::session_handlers::fence_session_handoff_handler),
        )
        .route(
            "/sessions/{session_id}/handoffs/{handoff_id}/activate",
            post(session::session_handlers::activate_session_handoff_handler),
        )
        .route(
            "/sessions/{session_id}/todos:execute",
            post(session::session_todo_handlers::execute_todo_handler),
        )
        .route(
            "/sessions/{session_id}/todos",
            get(session::session_todo_handlers::load_todos_handler),
        )
        .route(
            "/users/me/todos",
            get(session::session_todo_handlers::list_user_todos_handler),
        )
        .route(
            "/sessions/{session_id}/cancel",
            post(session::session_handlers::cancel_session_handler),
        )
        .route(
            "/sessions/{session_id}/activity",
            get(session::session_handlers::session_activity_handler),
        )
        .route(
            "/sessions/{session_id}/artifacts",
            get(session::session_handlers::list_session_artifacts_handler),
        )
        .route(
            "/sessions/{session_id}/artifacts/latest/{artifact_kind}",
            get(session::session_handlers::get_latest_session_artifact_handler),
        )
        .route(
            "/sessions/{session_id}/artifacts/{artifact_id}",
            get(session::session_handlers::get_session_artifact_handler),
        )
        .route(
            "/sessions/{session_id}/artifacts/{artifact_id}/download",
            get(session::session_handlers::download_session_artifact_handler),
        )
        .nest(
            "/sessions/{session_id}/harness",
            harness_routes(state.clone()),
        )
        .route(
            "/sessions/{session_id}/replay",
            post(crate::service_handlers::replay::replay_session_handler),
        )
        .route(
            "/sessions/{session_id}/replay/compare",
            get(crate::service_handlers::replay::compare_replay_handler),
        )
        .route(
            "/sessions/{session_id}/audit/summary",
            get(audit_handlers::audit_summary_handler),
        )
        .route(
            "/sessions/{session_id}/audit/turns",
            get(audit_handlers::audit_turns_handler),
        )
        .route(
            "/sessions/{session_id}/audit/turns/{turn}",
            get(audit_handlers::audit_turn_detail_handler),
        )
        .route(
            "/sessions/{session_id}/audit/context-traces",
            get(audit_handlers::audit_context_traces_handler),
        )
        .route(
            "/sessions/{session_id}/audit/tools",
            get(audit_handlers::audit_tools_handler),
        )
        .route(
            "/sessions/{session_id}/audit/errors",
            get(audit_handlers::audit_errors_handler),
        )
        .route(
            "/sessions/{session_id}/audit/promotions",
            get(audit_handlers::audit_runtime_promotions_handler),
        )
        .route(
            "/audit/sessions",
            get(audit_handlers::list_sessions_handler),
        )
        .route(
            "/audit/stats",
            get(audit_handlers::cross_session_stats_handler),
        )
        .route(
            "/audit/tools",
            get(audit_handlers::cross_session_tools_handler),
        )
        .route(
            "/audit/promotions",
            get(audit_handlers::cross_session_runtime_promotions_handler),
        )
}

#[cfg(feature = "harness")]
fn harness_routes(state: AppState) -> Router<AppState> {
    use axum::routing::get;
    Router::new()
        .route(
            "/snapshot",
            get(crate::server::harness::handlers::get_harness_snapshot),
        )
        .route(
            "/history",
            get(crate::server::harness::handlers::get_harness_history),
        )
        .route(
            "/diff",
            get(crate::server::harness::handlers::get_harness_diff),
        )
        .route(
            "/stream",
            get(crate::server::harness::handlers::stream_harness_snapshots),
        )
        .with_state(state)
}

#[cfg(not(feature = "harness"))]
fn harness_routes(_state: AppState) -> Router<AppState> {
    Router::new()
}
