//! Shared handler for the consolidated `agent` tool.
//!
//! CLI and server execution environments own different child-loop
//! executors, but the `agent(action='spawn'|'get_result')` contract is
//! runtime semantics. Keep parsing, normalization, lifecycle dispatch, and
//! result rendering here so Web/server cannot drift from CLI behavior.

use serde_json::{Value, json};
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use super::{
    DynamicAgentSpawner, InheritedPermissions, SpawnAgentInput, SpawnContext, WaitForAgentOutcome,
};
use astra_turn_core::trace_event::TraceContext;

/// Maximum byte length we accept for an `agent_id` argument before
/// rejecting the request without echoing the value. Bytes (not chars)
/// because the limit is really about prompt-injection / log-bloat budget.
const MAX_AGENT_ID_BYTES: usize = 256;
const SPAWN_AGENT_ID_FIELD_ERROR: &str = "invalid `agent_id` field for agent.spawn. `agent_id` is \
runtime-generated by spawn and may only be used with \
`agent(action='get_result', agent_id='...')`. If you need an \
addressable mailbox name for `send_message`, use `name`.";
/// Static prose for the `Unknown` outcome. Must NOT interpolate the
/// caller-supplied agent_id — that value already appears in the
/// structured `agent_id` JSON field, where serde escapes it safely.
const UNKNOWN_AGENT_ID_ERROR: &str = "Unknown agent_id. Use the exact runtime-generated agent_id returned by the earlier spawn result. The optional spawn `name` is only for send_message addressing and cannot be used with get_result.";

/// Context for executing `agent` tool lifecycle actions.
#[derive(Clone)]
pub struct AgentToolContext {
    /// Current agent's run ID.
    pub run_id: String,
    /// Current agent's ID.
    pub agent_id: String,
    /// Current active model for the parent turn. Used as the default
    /// child model when the tool call omits an explicit override.
    pub current_model: Option<String>,
    /// Current nested agent/sub-run depth of the agent.
    pub recursion_depth: u8,
    /// Whether this agent already inherited a fork prefix.
    pub is_fork_child: bool,
    /// Working directory inherited by the child unless isolation changes it.
    pub working_dir: PathBuf,
    /// Shared lifecycle owner for dynamic child agents.
    pub spawner: Arc<DynamicAgentSpawner>,
    /// Effective permissions inherited by children spawned from this agent.
    pub inherited_permissions: InheritedPermissions,
    /// Skills available to this agent and inherited by children.
    pub active_skills: Vec<String>,
    /// Optional sink for live child token/tool/status events.
    pub live_event_sink: Option<astra_turn_core::agent_live_event::SharedAgentLiveEventSink>,
    /// DB trace identity shared with the current Web turn.
    pub trace_context: Option<TraceContext>,
}

/// Handle the consolidated `agent` tool for shared dynamic-agent actions.
///
/// Environment-specific actions such as `run_chain` can still be handled by
/// the caller before/after this function. This shared handler intentionally
/// owns spawn/get_result validation and rendering.
pub async fn handle_agent_tool(args: &Value, ctx: Option<&AgentToolContext>) -> String {
    let action = args.get("action").and_then(Value::as_str).unwrap_or("");
    match action {
        "spawn" => handle_agent_spawn_action(args, ctx).await,
        "get_result" => handle_agent_get_result_action(args, ctx).await,
        "send_message" => json!({
            "status": "failed",
            "error": "agent.send_message requires a mailbox-aware executor and is not handled by the shared spawn/get_result runtime handler."
        })
        .to_string(),
        other if other.is_empty() && args.get("spawn").is_some() => json!({
            "status": "failed",
            "error": "Invalid agent call shape. Use the top-level `action='spawn'` field, not a `spawn` wrapper key. Example: agent(action='spawn', description='...', prompt='...', run_in_background: true)."
        })
        .to_string(),
        other if other.is_empty() && args.get("agents").is_some() => json!({
            "status": "failed",
            "error": "Unsupported `agents` batch payload for `agent`. Each `agent(action='spawn', ...)` call launches exactly one child. To fan out in parallel, emit N separate spawn calls in a single assistant message."
        })
        .to_string(),
        other => json!({
            "status": "failed",
            "error": format!("Unknown agent action: '{other}'. Use one of: spawn, get_result, run_chain")
        })
        .to_string(),
    }
}

/// Handle `agent(action='spawn')`.
pub async fn handle_agent_spawn_action(args: &Value, ctx: Option<&AgentToolContext>) -> String {
    let mut input: SpawnAgentInput = match normalize_agent_spawn_args(args)
        .and_then(|patched_args| serde_json::from_value(patched_args).map_err(|e| e.to_string()))
    {
        Ok(i) => i,
        Err(e) => {
            return json!({
                "status": "failed",
                "error": format!("Invalid input: {e}")
            })
            .to_string();
        }
    };

    let ctx = match ctx {
        Some(c) => c,
        None => {
            return json!({
                "status": "failed",
                "error": "Agent spawning not available in this context."
            })
            .to_string();
        }
    };

    if input.model.is_none() {
        input.model = ctx.current_model.clone();
    }

    let mut inherited_permissions = ctx.inherited_permissions.clone();
    inherited_permissions.is_background = input.run_in_background;
    let spawn_ctx = SpawnContext {
        parent_run_id: ctx.run_id.clone(),
        parent_agent_id: ctx.agent_id.clone(),
        recursion_depth: ctx.recursion_depth,
        parent_is_fork_child: ctx.is_fork_child,
        working_dir: ctx.working_dir.clone(),
        inherited_permissions: Some(inherited_permissions),
        inherited_skills: ctx.active_skills.clone(),
        live_event_sink: ctx.live_event_sink.clone(),
        trace_context: ctx.trace_context.clone(),
        spawn_tool_call_id: args
            .get("_tool_call_id")
            .and_then(Value::as_str)
            .map(ToString::to_string),
    };

    match ctx.spawner.spawn(input, &spawn_ctx).await {
        Ok(output) => serde_json::to_string(&output).unwrap_or_else(|_| {
            json!({
                "status": "failed",
                "error": "Failed to serialize output"
            })
            .to_string()
        }),
        Err(e) => json!({
            "status": "failed",
            "error": e.to_string()
        })
        .to_string(),
    }
}

fn non_empty_string(value: Option<&Value>) -> Option<&str> {
    value
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
}

fn summarize_prompt(prompt: &str) -> String {
    const MAX_DESCRIPTION_CHARS: usize = 60;
    if prompt.chars().count() > MAX_DESCRIPTION_CHARS {
        let truncated: String = prompt
            .chars()
            .take(MAX_DESCRIPTION_CHARS.saturating_sub(1))
            .collect();
        format!("{}…", truncated.trim_end())
    } else {
        prompt.to_string()
    }
}

/// Normalize raw `agent(action='spawn', ...)` arguments into
/// [`SpawnAgentInput`] wire shape.
///
/// Existing CLI behavior accepts either `prompt` or `description` and derives
/// the missing counterpart. The shared runtime keeps that compatibility while
/// still rejecting batch/wrapper/deprecated shapes explicitly.
pub fn normalize_agent_spawn_args(args: &Value) -> Result<Value, String> {
    let mut patched_args = args.clone();
    let obj = patched_args
        .as_object_mut()
        .ok_or_else(|| "spawn input must be a JSON object".to_string())?;

    if obj.contains_key("spawn") {
        return Err("invalid `spawn` wrapper for agent.spawn: use top-level fields with `action='spawn'`, for example `agent(action='spawn', description='...', prompt='...')`."
            .to_string());
    }

    if obj.contains_key("agents") {
        return Err("unsupported `agents` payload for agent.spawn: each \
             `agent(action='spawn', ...)` call launches exactly one child. \
             To fan out N sub-agents in parallel, emit N separate `agent` \
             tool calls in a single assistant message, each with \
             `action='spawn'` and `run_in_background: true`."
            .to_string());
    }

    if obj.contains_key("task") {
        return Err("unsupported deprecated `task` field for agent.spawn. \
             Use top-level `prompt` for the full child task brief and \
             `description` for the short UI summary."
            .to_string());
    }

    if obj.contains_key("agent_id") {
        return Err(SPAWN_AGENT_ID_FIELD_ERROR.to_string());
    }

    let description = non_empty_string(obj.get("description")).map(str::to_string);
    let prompt = non_empty_string(obj.get("prompt")).map(str::to_string);
    if description.is_none() && prompt.is_none() {
        return Err("missing required field `prompt` or `description`".to_string());
    }

    if description.is_none() {
        let derived = summarize_prompt(prompt.as_deref().expect("checked above"));
        obj.insert("description".to_string(), Value::String(derived));
    }

    if prompt.is_none() {
        let derived = description.expect("checked above");
        obj.insert("prompt".to_string(), Value::String(derived));
    }

    Ok(patched_args)
}

/// Handle `agent(action='get_result')`.
pub async fn handle_agent_get_result_action(
    args: &Value,
    ctx: Option<&AgentToolContext>,
) -> String {
    let agent_id = match args.get("agent_id").and_then(Value::as_str).map(str::trim) {
        Some(id) if !id.is_empty() => id,
        None => {
            return json!({
                "status": "failed",
                "error": "Missing required field: agent_id"
            })
            .to_string();
        }
        Some(_) => {
            return json!({
                "status": "failed",
                "error": "Invalid agent_id: must be a non-empty string"
            })
            .to_string();
        }
    };

    let ctx = match ctx {
        Some(c) => c,
        None => {
            return json!({
                "status": "failed",
                "error": "Agent spawning not available in this context."
            })
            .to_string();
        }
    };

    use astra_turn_core::orchestration_types::AgentStatus;

    if agent_id.len() > MAX_AGENT_ID_BYTES {
        return json!({
            "status": "failed",
            "error": format!("Invalid agent_id: exceeds {MAX_AGENT_ID_BYTES} bytes"),
        })
        .to_string();
    }

    let timeout = Duration::from_secs(120);
    match ctx.spawner.wait_for_agent_outcome(agent_id, timeout).await {
        WaitForAgentOutcome::Status(status) => {
            ctx.spawner
                .record_agent_result_collected(
                    &ctx.run_id,
                    &ctx.agent_id,
                    agent_id,
                    args.get("_tool_call_id").and_then(Value::as_str),
                    &status,
                )
                .await;
            match status {
                AgentStatus::Completed {
                    result,
                    finish_reason,
                } => render_completed_agent_result(agent_id, &result, finish_reason.as_deref()),
                AgentStatus::Failed {
                    error,
                    finish_reason,
                } => {
                    let reason = finish_reason.as_deref().unwrap_or("failed");
                    json!({
                        "status": "failed",
                        "agent_id": agent_id,
                        "error": error,
                        "finish_reason": reason,
                    })
                    .to_string()
                }
                status => json!({
                    "status": "unknown",
                    "agent_id": agent_id,
                    "detail": format!("{status:?}"),
                })
                .to_string(),
            }
        }
        WaitForAgentOutcome::TimedOut => {
            let live_status = ctx
                .spawner
                .get_agent_state_any(agent_id)
                .await
                .map(|state| state.status);
            render_wait_timeout_outcome(agent_id, live_status.as_ref(), timeout)
        }
        WaitForAgentOutcome::Unknown => json!({
            "status": "failed",
            "agent_id": agent_id,
            "error": UNKNOWN_AGENT_ID_ERROR,
        })
        .to_string(),
    }
}

pub fn render_completed_agent_result(
    agent_id: &str,
    result: &str,
    finish_reason: Option<&str>,
) -> String {
    let reason = finish_reason.unwrap_or("normal");
    let interrupted = reason != "normal";
    let mut body = json!({
        "status": if interrupted { "interrupted" } else { "completed" },
        "agent_id": agent_id,
        "result": result,
        "finish_reason": reason,
        "incomplete": interrupted,
    });
    if interrupted {
        body["hint"] = json!(
            "The child agent stopped before fully finishing. Treat this as incomplete and either continue it or report the interruption explicitly."
        );
    }
    body.to_string()
}

/// Decide the outcome JSON when `wait_for_agent` returns `None`.
///
/// Split out as a pure function so timeout vs still-running remains
/// regression-tested without standing up a full [`DynamicAgentSpawner`].
pub fn render_wait_timeout_outcome(
    agent_id: &str,
    live_status: Option<&astra_turn_core::orchestration_types::AgentStatus>,
    timeout: Duration,
) -> String {
    match live_status {
        Some(status) if !status.is_terminal() => json!({
            "status": "still_running",
            "agent_id": agent_id,
            "current_status": format!("{status:?}"),
            "waited_secs": timeout.as_secs(),
            "hint": "The child agent is still working. Call `agent(action='get_result', agent_id=...)` again \
                    to continue waiting. Do NOT treat this as failure or fabricate \
                    what the child would have returned.",
        })
        .to_string(),
        _ => json!({
            "status": "timeout",
            "agent_id": agent_id,
            "error": format!(
                "Agent '{agent_id}' did not complete within {}s and has no live state",
                timeout.as_secs()
            ),
        })
        .to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::orchestration::{SpawnAgentExecutor, SpawnRunConfig, SpawnRunResult};
    use crate::server::delegation::engine::DelegationTracker;
    use astra_turn_core::orchestration_types::AgentStatus;
    use std::sync::Mutex;

    #[tokio::test]
    async fn spawn_invalid_input_fails_before_context_lookup() {
        let result = handle_agent_spawn_action(&json!({"invalid": "data"}), None).await;
        assert!(result.contains("Invalid input"), "{result}");
        assert!(result.contains("\"status\":\"failed\""), "{result}");
    }

    #[tokio::test]
    async fn spawn_rejects_null_and_non_object_inputs() {
        for args in [Value::Null, json!("spawn"), json!(["prompt"])] {
            let result = handle_agent_spawn_action(&args, None).await;
            assert!(result.contains("Invalid input"), "{result}");
            assert!(result.contains("\"status\":\"failed\""), "{result}");
        }
    }

    #[test]
    fn spawn_arg_normalization_derives_description_from_unicode_prompt() {
        let prompt = "审查并发安全、事件顺序、日志因果链、用户交互、失败恢复、批处理、取消传播、状态渲染、详情页滚动".repeat(2);
        let normalized = normalize_agent_spawn_args(&json!({ "prompt": prompt })).unwrap();
        let desc = normalized["description"].as_str().unwrap();
        assert!(desc.ends_with('…'), "{desc}");
        assert!(desc.chars().count() <= 60);
        assert_eq!(normalized["prompt"].as_str().unwrap(), prompt);
    }

    #[test]
    fn spawn_arg_normalization_derives_prompt_from_description() {
        let normalized =
            normalize_agent_spawn_args(&json!({ "description": "Review auth flow" })).unwrap();
        assert_eq!(normalized["prompt"], "Review auth flow");
        assert_eq!(normalized["description"], "Review auth flow");
    }

    #[test]
    fn spawn_arg_normalization_rejects_legacy_task_field() {
        let err = normalize_agent_spawn_args(&json!({
            "description": "Audit auth flow",
            "task": "Read src/auth and report token refresh bugs."
        }))
        .expect_err("deprecated task field must be rejected");
        assert!(
            err.contains("deprecated `task` field") && err.contains("prompt"),
            "migration error must tell callers to move to prompt. Got: {err}"
        );
    }

    #[test]
    fn spawn_arg_normalization_rejects_agent_id_field() {
        let err = normalize_agent_spawn_args(&json!({
            "description": "Audit auth flow",
            "prompt": "Read src/auth and report token refresh bugs.",
            "agent_id": "security-review"
        }))
        .expect_err("spawn must reject caller-supplied agent_id");
        assert!(err.contains("invalid `agent_id` field"), "{err}");
        assert!(err.contains("runtime-generated"), "{err}");
        assert!(err.contains("name"), "{err}");
    }

    #[test]
    fn spawn_arg_normalization_rejects_task_even_when_prompt_is_present() {
        let err = normalize_agent_spawn_args(&json!({
            "description": "Audit auth flow",
            "prompt": "Use the new prompt field.",
            "task": "Do not use this deprecated alias."
        }))
        .expect_err("deprecated task field must stay forbidden even when prompt exists");
        assert!(
            err.contains("deprecated `task` field"),
            "mixed prompt/task payloads must still hard-fail. Got: {err}"
        );
    }

    #[test]
    fn spawn_arg_normalization_never_fabricates_placeholder_prompt() {
        let err = normalize_agent_spawn_args(&json!({ "name": "reviewer-only" }))
            .expect_err("name alone is not enough to spawn a meaningful agent");
        assert!(
            err.contains("prompt") || err.contains("description"),
            "{err}"
        );
    }

    #[test]
    fn spawn_arg_normalization_rejects_agents_batch_payload_with_redirect() {
        let err = normalize_agent_spawn_args(&json!({
            "action": "spawn",
            "agents": [
                {"description": "Review one", "prompt": "p1"},
                {"description": "Review two", "prompt": "p2"}
            ]
        }))
        .expect_err("batch payloads must be rejected with an actionable redirect");
        assert!(err.contains("agents"), "{err}");
        assert!(
            err.contains("single assistant message") || err.contains("separate"),
            "error must explain the supported fan-out shape. Got: {err}"
        );
    }

    #[test]
    fn spawn_arg_normalization_rejects_spawn_wrapper_payload() {
        let err = normalize_agent_spawn_args(&json!({
            "spawn": {"description": "Review one", "prompt": "p1"}
        }))
        .expect_err("wrapper payloads must be rejected");
        assert!(err.contains("wrapper"), "{err}");
        assert!(err.contains("top-level"), "{err}");
    }

    #[test]
    fn spawn_arg_normalization_accepts_run_in_background_alias() {
        let normalized = normalize_agent_spawn_args(&json!({
            "description": "Review one",
            "prompt": "p1",
            "run_in_background": true
        }))
        .unwrap();
        let input: SpawnAgentInput = serde_json::from_value(normalized).unwrap();
        assert!(input.run_in_background);
    }

    #[tokio::test]
    async fn spawn_no_context_fails_explicitly() {
        let args = json!({
            "description": "Test",
            "prompt": "Test prompt"
        });
        let result = handle_agent_spawn_action(&args, None).await;
        assert!(result.contains("not available"));
        assert!(result.contains("\"status\":\"failed\""), "{result}");
    }

    struct CapturingModelExecutor {
        captured_model: Mutex<Option<String>>,
    }

    impl CapturingModelExecutor {
        fn new() -> Self {
            Self {
                captured_model: Mutex::new(None),
            }
        }

        fn take_captured_model(&self) -> Option<String> {
            self.captured_model.lock().unwrap().take()
        }
    }

    #[async_trait::async_trait]
    impl SpawnAgentExecutor for CapturingModelExecutor {
        async fn execute(&self, config: SpawnRunConfig) -> Result<SpawnRunResult, String> {
            *self.captured_model.lock().unwrap() = config.model.clone();
            Ok(SpawnRunResult {
                agent_id: config.agent_id,
                run_id: config.run_id,
                status: "completed".into(),
                finish_reason: "normal".into(),
                output: Some("ok".into()),
                error: None,
                prompt_tokens: 0,
                completion_tokens: 0,
                tool_calls: 0,
                permission_summary: None,
                permission_requests: 0,
                permission_requests_approved: 0,
                tools_blocked: 0,
            })
        }
    }

    fn test_spawner(executor: Arc<dyn SpawnAgentExecutor>) -> Arc<DynamicAgentSpawner> {
        let transport = Arc::new(astra_messaging::InProcessTransport::new());
        let tracker = Arc::new(DelegationTracker::new());
        let router = Arc::new(astra_messaging::AgentMailboxRouter::new(transport, tracker));
        Arc::new(DynamicAgentSpawner::new(router).with_executor(executor))
    }

    fn test_spawn_context(
        spawner: Arc<DynamicAgentSpawner>,
        current_model: Option<&str>,
    ) -> AgentToolContext {
        AgentToolContext {
            run_id: "run-parent".into(),
            agent_id: "root-agent".into(),
            current_model: current_model.map(str::to_string),
            recursion_depth: 0,
            is_fork_child: false,
            working_dir: PathBuf::from("."),
            spawner,
            inherited_permissions: InheritedPermissions::auto_approve(),
            active_skills: Vec::new(),
            live_event_sink: None,
            trace_context: None,
        }
    }

    #[tokio::test]
    async fn handle_spawn_agent_tool_inherits_parent_model_when_omitted() {
        let executor = Arc::new(CapturingModelExecutor::new());
        let spawner = test_spawner(executor.clone());
        let ctx = test_spawn_context(spawner, Some("MiniMax-M2.7"));
        let args = json!({
            "description": "Code quality review",
            "prompt": "Review the latest commit",
            "agent_type": "general-purpose"
        });

        let result = handle_agent_spawn_action(&args, Some(&ctx)).await;

        assert!(result.contains("\"status\":\"completed\""), "{result}");
        assert_eq!(
            executor.take_captured_model().as_deref(),
            Some("MiniMax-M2.7")
        );
    }

    #[tokio::test]
    async fn handle_spawn_agent_tool_preserves_explicit_model_override() {
        let executor = Arc::new(CapturingModelExecutor::new());
        let spawner = test_spawner(executor.clone());
        let ctx = test_spawn_context(spawner, Some("MiniMax-M2.7"));
        let args = json!({
            "description": "Code quality review",
            "prompt": "Review the latest commit",
            "agent_type": "general-purpose",
            "model": "claude-sonnet-4.6"
        });

        let result = handle_agent_spawn_action(&args, Some(&ctx)).await;

        assert!(result.contains("\"status\":\"completed\""), "{result}");
        assert_eq!(
            executor.take_captured_model().as_deref(),
            Some("claude-sonnet-4.6")
        );
    }

    #[tokio::test]
    async fn get_agent_result_missing_agent_id() {
        let result = handle_agent_get_result_action(&json!({}), None).await;
        assert!(result.contains("Missing required field"));
        assert!(result.contains("\"status\":\"failed\""), "{result}");
    }

    #[tokio::test]
    async fn get_agent_result_no_context() {
        let result = handle_agent_get_result_action(&json!({"agent_id": "child-1"}), None).await;
        assert!(result.contains("not available"));
        assert!(result.contains("\"status\":\"failed\""), "{result}");
    }

    #[tokio::test]
    async fn get_agent_result_unknown_agent_id_fails_explicitly() {
        let executor = Arc::new(CapturingModelExecutor::new());
        let spawner = test_spawner(executor);
        let ctx = test_spawn_context(spawner, Some("MiniMax-M2.7"));

        let result =
            handle_agent_get_result_action(&json!({"agent_id": "security-review"}), Some(&ctx))
                .await;
        let value: Value = serde_json::from_str(&result).unwrap();
        assert_eq!(value["status"], "failed");
        assert_eq!(value["agent_id"], "security-review");
        assert!(
            value["error"]
                .as_str()
                .unwrap_or("")
                .contains("exact runtime-generated agent_id"),
            "{result}"
        );
        assert!(
            value["error"].as_str().unwrap_or("").contains("name"),
            "{result}"
        );
    }

    #[tokio::test]
    async fn get_agent_result_rejects_overlong_agent_id_without_echoing_it() {
        let executor = Arc::new(CapturingModelExecutor::new());
        let spawner = test_spawner(executor);
        let ctx = test_spawn_context(spawner, Some("MiniMax-M2.7"));
        let huge = "a".repeat(MAX_AGENT_ID_BYTES + 1);

        let result = handle_agent_get_result_action(&json!({"agent_id": huge}), Some(&ctx)).await;
        let value: Value = serde_json::from_str(&result).unwrap();
        assert_eq!(value["status"], "failed");
        let expected_msg = format!("exceeds {MAX_AGENT_ID_BYTES} bytes");
        assert!(
            value["error"]
                .as_str()
                .unwrap_or("")
                .contains(&expected_msg),
            "{result}"
        );
        // No fragment of the oversized id should appear anywhere in the
        // returned tool output (neither prose nor the structured field).
        // 16 bytes is short enough to be a sensitive prefix and long enough
        // that it cannot occur incidentally.
        assert!(
            !result.contains(&"a".repeat(16)),
            "error must not echo attacker-controlled oversized ids: {result}"
        );
    }

    #[tokio::test]
    async fn shared_handler_rejects_send_message_without_mailbox_executor() {
        let result = handle_agent_tool(
            &json!({
                "action": "send_message",
                "to": "agent-1",
                "message": "hello"
            }),
            None,
        )
        .await;
        let value: Value = serde_json::from_str(&result).unwrap();
        assert_eq!(value["status"], "failed");
        assert!(
            value["error"]
                .as_str()
                .unwrap_or("")
                .contains("mailbox-aware executor"),
            "{result}"
        );
    }

    #[test]
    fn wait_timeout_still_running_when_live_state_non_terminal() {
        let status = AgentStatus::Running {
            activity: "reading file".into(),
        };
        let out =
            render_wait_timeout_outcome("reviewer-tests", Some(&status), Duration::from_secs(120));
        let v: Value = serde_json::from_str(&out).unwrap();
        assert_eq!(
            v["status"], "still_running",
            "a timeout while the child is demonstrably running must NOT look like failure: {out}"
        );
        assert!(
            v["hint"].as_str().unwrap_or("").contains("still working"),
            "the hint must tell the LLM to call again rather than synthesize a fake result: {out}"
        );
        assert_eq!(v["waited_secs"], 120);
    }

    #[test]
    fn wait_timeout_timeout_when_no_live_state() {
        let out = render_wait_timeout_outcome("unknown-agent", None, Duration::from_secs(120));
        let v: Value = serde_json::from_str(&out).unwrap();
        assert_eq!(
            v["status"], "timeout",
            "when there is no live state the outcome is a genuine timeout: {out}"
        );
        assert!(
            v["error"].as_str().unwrap_or("").contains("no live state"),
            "error must make the distinction auditable: {out}"
        );
    }

    #[test]
    fn wait_timeout_reports_terminal_states_as_timeout_not_still_running() {
        for terminal in [
            AgentStatus::Cancelled,
            AgentStatus::Failed {
                error: "x".into(),
                finish_reason: None,
            },
            AgentStatus::Completed {
                result: "done".into(),
                finish_reason: None,
            },
        ] {
            let out = render_wait_timeout_outcome("ag", Some(&terminal), Duration::from_secs(30));
            let v: Value = serde_json::from_str(&out).unwrap();
            assert_eq!(
                v["status"], "timeout",
                "terminal state must not render as still_running: status={terminal:?} out={out}"
            );
        }
    }

    #[test]
    fn completed_result_reports_budget_exhaustion_as_interrupted() {
        let out = render_completed_agent_result(
            "reviewer-tests",
            "partial findings",
            Some("budget_exhausted"),
        );
        let v: Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["status"], "interrupted");
        assert_eq!(v["finish_reason"], "budget_exhausted");
        assert_eq!(v["incomplete"], true);
        assert!(
            v["hint"].as_str().unwrap_or("").contains("incomplete"),
            "{out}"
        );
    }

    #[test]
    fn completed_result_keeps_normal_completion_completed() {
        let out = render_completed_agent_result("reviewer-tests", "done", Some("normal"));
        let v: Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["status"], "completed");
        assert_eq!(v["finish_reason"], "normal");
        assert_eq!(v["incomplete"], false);
        assert!(v.get("hint").is_none(), "{out}");
    }
}
