[package]
name = "astra-credentials"
version.workspace = true
edition.workspace = true

[dependencies]
dirs.workspace = true
fs2.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
temp-env.workspace = true
tempfile.workspace = true
