{{- if .Values.api.serverConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-server-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: astra
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: server
data:
  server.toml: |
{{ .Values.api.serverConfig.content | nindent 4 }}
{{- end }}
