apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: mo-agent
    component: api
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.api.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: mo-agent
    component: api
---
{{- if .Values.modelServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-model-server
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.modelServer.port }}
    targetPort: {{ .Values.modelServer.port }}
    name: http
  selector:
    app: mo-agent
    component: model-server
{{- end }}
---
{{- if .Values.matrixone.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-matrixone
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.matrixone.port }}
    targetPort: {{ .Values.matrixone.port }}
    name: mysql
  selector:
    app: mo-agent
    component: matrixone
{{- end }}
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
    name: redis
  selector:
    app: mo-agent
    component: redis
{{- end }}
