[package]
name = "astra-admin-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "astra-admin"
path = "src/main.rs"

[dependencies]
mo-thin-client.workspace = true
clap = { version = "4.5.38", features = ["derive"] }
crossterm = "0.27"
dirs = "6.0.0"
dotenvy.workspace = true
rpassword = "7"
rustyline = { version = "14", features = ["with-file-history"] }
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9.34"
tokio.workspace = true
