import type { OverviewData } from '@/lib/models/platform';

export const mockPlatformSnapshot: OverviewData = {
  health: {
    status: 'healthy',
    database: 'connected',
    persistOk: 1842,
    persistFail: 2,
  },
  stats: {
    activeAgents: 2,
    openSessions: 2,
    recentEvents: 4,
    persistOk: 1842,
  },
  agents: [
    {
      id: 'agent-orchestrator',
      name: 'Orchestrator',
      type: 'orchestrator',
      owner: 'system',
      model: 'gpt-5.4',
      status: 'active',
      skills: ['planning', 'delegation', 'audit'],
    },
    {
      id: 'agent-code-review',
      name: 'Code Review',
      type: 'user',
      owner: 'xupeng',
      model: 'claude-sonnet-4.6',
      status: 'active',
      skills: ['git', 'diff', 'analysis'],
    },
    {
      id: 'agent-ci',
      name: 'CI Diagnosis',
      type: 'user',
      owner: 'xupeng',
      model: 'gpt-5.4-mini',
      status: 'inactive',
      skills: ['actions', 'logs', 'tests'],
    },
  ],
  sessions: [
    {
      id: 'sess_8d2',
      title: 'Fix failing replay path',
      owner: 'xupeng',
      status: 'open',
      eventCount: 18,
      createdAt: '2026-03-30T06:10:00Z',
      updatedAt: '2026-03-30T06:49:00Z',
    },
    {
      id: 'sess_9k4',
      title: 'Plan frontend platform',
      owner: 'xupeng',
      status: 'waiting',
      eventCount: 9,
      createdAt: '2026-03-30T06:55:00Z',
      updatedAt: '2026-03-30T07:15:00Z',
    },
    {
      id: 'sess_1fa',
      title: 'Nightly governance sweep',
      owner: 'system',
      status: 'closed',
      eventCount: 31,
      createdAt: '2026-03-30T05:40:00Z',
      updatedAt: '2026-03-30T06:20:00Z',
    },
  ],
  events: [
    {
      id: 'evt_901',
      sessionId: 'sess_9k4',
      type: 'plan_created',
      summary: 'Initial platform dashboard plan persisted.',
      agentId: 'agent-orchestrator',
      createdAt: 'just now',
    },
    {
      id: 'evt_902',
      sessionId: 'sess_8d2',
      type: 'delegate_task',
      summary: 'Code review agent delegated to inspect staged diff.',
      agentId: 'agent-code-review',
      createdAt: '12 min ago',
    },
    {
      id: 'evt_903',
      sessionId: 'sess_8d2',
      type: 'run_waiting',
      summary: 'Run paused pending CI completion event.',
      agentId: 'agent-ci',
      createdAt: '9 min ago',
    },
    {
      id: 'evt_904',
      sessionId: 'sess_1fa',
      type: 'run_completed',
      summary: 'Governance sweep wrote audit and cleanup summary.',
      agentId: 'agent-orchestrator',
      createdAt: '37 min ago',
    },
  ],
};
