use serde::{Deserialize, Serialize};

/// Intent type for tag-based pre-filtering.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IntentType {
    /// Code editing, file manipulation, builds
    CodeEdit,
    /// Read-only inspection, search, navigation
    CodeRead,
    /// Git operations (status, diff, log)
    Git,
    /// GitHub API (PRs, issues, CI)
    GitHub,
    /// Memory storage/retrieval
    Memory,
    /// Agent introspection, reflection
    Introspect,
    /// Database operations (MatrixOne query, snapshot, branch)
    Database,
}

impl IntentType {
    /// Get the snake_case string representation of this intent type.
    pub fn as_str(&self) -> &'static str {
        match self {
            IntentType::CodeEdit => "code_edit",
            IntentType::CodeRead => "code_read",
            IntentType::Git => "git",
            IntentType::GitHub => "github",
            IntentType::Memory => "memory",
            IntentType::Introspect => "introspect",
            IntentType::Database => "database",
        }
    }
}

/// Data source scope for tag-based pre-filtering.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Scope {
    /// Local filesystem operations
    Local,
    /// Local git repository
    LocalGit,
    /// External API calls (GitHub, etc.)
    External,
    /// Cross-session persistent store (memory)
    CrossSession,
}

/// Static metadata for a tool — used for selection, never sent to LLM.
#[derive(Debug, Clone)]
pub struct ToolMeta {
    /// Tool function name (e.g. "bash", "github_list_prs")
    pub name: &'static str,
    /// Short description for embedding index
    pub description: &'static str,
    /// Trigger phrases — additional semantic signals for retrieval
    pub triggers: &'static [&'static str],
    /// Whether this tool is always included (no selection needed)
    pub pinned: bool,
    /// Intent classification tags
    pub intents: &'static [IntentType],
    /// Data source scope
    pub scope: Scope,
    /// Estimated token cost of the full JSON schema (~JSON bytes / 4)
    pub schema_tokens: u32,
}

// ─── Tool catalog ───────────────────────────────────────────────────────────

/// Complete catalog of all tools with their metadata.
///
/// Cross-language coverage comes from rich multilingual triggers — each tool
/// includes Chinese and English synonyms, common abbreviations, and semantic
/// associations. This eliminates the need for embedding models while providing
/// deterministic, debuggable, zero-latency matching.
pub static TOOL_CATALOG: &[ToolMeta] = &[
    // ── Pinned tools (always available) ─────────────────────────────
    ToolMeta {
        name: "bash",
        description: "Execute shell commands for builds, tests, installs, git, CLI tasks",
        triggers: &[
            "run", "execute", "build", "test", "install", "command", "shell", "script", "compile",
            "运行", "执行", "编译", "测试", "安装", "命令", "脚本",
        ],
        pinned: true,
        intents: &[IntentType::CodeEdit, IntentType::CodeRead, IntentType::Git],
        scope: Scope::Local,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "read_file",
        description: "Read file contents with optional line range",
        triggers: &[
            "read",
            "view",
            "show",
            "inspect",
            "look at",
            "open",
            "cat",
            "display",
            "查看",
            "读取",
            "打开",
            "看看",
            "看一下",
            "文件内容",
        ],
        pinned: true,
        intents: &[IntentType::CodeRead],
        scope: Scope::Local,
        schema_tokens: 35,
    },
    ToolMeta {
        name: "write_file",
        description: "Create or overwrite a file",
        triggers: &[
            "write",
            "create file",
            "save file",
            "output",
            "generate file",
            "write to",
            "创建文件",
            "写入",
            "保存文件",
            "生成文件",
            "写文件",
        ],
        pinned: true,
        intents: &[IntentType::CodeEdit],
        scope: Scope::Local,
        schema_tokens: 25,
    },
    ToolMeta {
        name: "str_replace",
        description: "Replace text in files with exact string matching",
        triggers: &[
            "replace",
            "edit",
            "modify",
            "update",
            "fix",
            "refactor",
            "rename",
            "替换",
            "修改",
            "编辑",
            "改代码",
            "改文件",
            "重构",
            "重命名",
        ],
        pinned: true,
        intents: &[IntentType::CodeEdit],
        scope: Scope::Local,
        schema_tokens: 40,
    },
    ToolMeta {
        name: "list_dir",
        description: "List directory structure and files",
        triggers: &[
            "list directory",
            "directory",
            "files",
            "list files",
            "tree",
            "structure",
            "folder",
            "目录",
            "文件列表",
            "文件夹",
            "结构",
        ],
        pinned: true,
        intents: &[IntentType::CodeRead],
        scope: Scope::Local,
        schema_tokens: 25,
    },
    ToolMeta {
        name: "grep",
        description: "Search file contents with regex patterns",
        triggers: &[
            "search",
            "find",
            "grep",
            "pattern",
            "match",
            "look for",
            "regex",
            "contain",
            "搜索",
            "查找",
            "查询代码",
            "搜索代码",
            "包含",
            "匹配",
        ],
        pinned: true,
        intents: &[IntentType::CodeRead],
        scope: Scope::Local,
        schema_tokens: 40,
    },
    ToolMeta {
        name: "glob",
        description: "Find files by name pattern",
        triggers: &[
            "find files",
            "glob",
            "locate",
            "file pattern",
            "find by name",
            "找文件",
            "文件名",
            "定位文件",
        ],
        pinned: true,
        intents: &[IntentType::CodeRead],
        scope: Scope::Local,
        schema_tokens: 25,
    },
    // ── Dynamic tools (selected per-request) ────────────────────────
    ToolMeta {
        name: "git_status",
        description: "Show git working tree status",
        triggers: &[
            "git status",
            "changes",
            "modified",
            "staged",
            "uncommitted",
            "working tree",
            "untracked",
            "dirty",
            "状态",
            "改了什么",
            "未提交",
            "暂存",
            "改了吗",
        ],
        pinned: false,
        intents: &[IntentType::Git],
        scope: Scope::LocalGit,
        schema_tokens: 15,
    },
    ToolMeta {
        name: "git_diff",
        description: "Show git diffs for files or commits",
        triggers: &[
            "diff",
            "difference",
            "compare",
            "changed",
            "what changed",
            "changes between",
            "review changes",
            "差异",
            "对比",
            "变更",
            "改动",
            "看改动",
        ],
        pinned: false,
        intents: &[IntentType::Git],
        scope: Scope::LocalGit,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "git_log",
        description: "Show git commit history",
        triggers: &[
            "log",
            "history",
            "commits",
            "recent commits",
            "commit history",
            "changelog",
            "recent changes",
            "commit list",
            "review commits",
            "local commits",
            "branch commits",
            "提交历史",
            "日志",
            "提交记录",
            "最近提交",
            "最近改动",
            "提交列表",
        ],
        pinned: false,
        intents: &[IntentType::Git],
        scope: Scope::LocalGit,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "git_show",
        description: "Show a specific commit's diff, message, author, and changes",
        triggers: &[
            "show commit",
            "commit diff",
            "commit detail",
            "review commit",
            "what changed in",
            "show sha",
            "git show",
            "commit content",
            "inspect commit",
            "查看提交",
            "提交详情",
            "这个提交改了什么",
            "review",
            "评审",
            "提交修改内容",
        ],
        pinned: false,
        intents: &[IntentType::Git],
        scope: Scope::LocalGit,
        schema_tokens: 40,
    },
    ToolMeta {
        name: "git_blame",
        description: "Show who last modified each line of a file with commit info",
        triggers: &[
            "blame",
            "who changed",
            "who wrote",
            "who modified",
            "line author",
            "code ownership",
            "annotate",
            "last modified",
            "谁改的",
            "谁写的",
            "代码归属",
            "行作者",
            "最后修改",
        ],
        pinned: false,
        intents: &[IntentType::Git],
        scope: Scope::LocalGit,
        schema_tokens: 35,
    },
    ToolMeta {
        name: "git_file_history",
        description: "Show change history for a specific file with rename tracking",
        triggers: &[
            "file history",
            "file changes",
            "file log",
            "who changed this file",
            "when was this changed",
            "file evolution",
            "change log",
            "文件历史",
            "文件变更",
            "谁改了这个文件",
            "文件改动记录",
        ],
        pinned: false,
        intents: &[IntentType::Git],
        scope: Scope::LocalGit,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "git_contributors",
        description: "Analyze repository contributors, hot files, and activity patterns",
        triggers: &[
            "contributors",
            "who contributed",
            "top authors",
            "hot files",
            "churn",
            "activity",
            "team",
            "codebase analytics",
            "who worked on",
            "author",
            "贡献者",
            "谁贡献的",
            "热点文件",
            "活跃度",
            "团队",
            "代码分析",
            "谁做的",
            "开发者",
        ],
        pinned: false,
        intents: &[IntentType::Git],
        scope: Scope::LocalGit,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "git_log_search",
        description: "Semantic search on commit messages using TF-IDF with CJK support",
        triggers: &[
            "search commits",
            "find commit",
            "when was",
            "commit search",
            "git search",
            "what commit",
            "who committed",
            "commit about",
            "搜索提交",
            "找提交",
            "什么时候",
            "提交搜索",
            "哪个提交",
        ],
        pinned: false,
        intents: &[IntentType::Git],
        scope: Scope::LocalGit,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "github_list_prs",
        description: "List pull requests for a GitHub repository",
        triggers: &[
            "pull request",
            "PRs",
            "list prs",
            "open prs",
            "merged",
            "merge request",
            "github pr",
            "最新的pr",
            "拉取请求",
            "合并请求",
            "pr列表",
        ],
        pinned: false,
        intents: &[IntentType::GitHub],
        scope: Scope::External,
        schema_tokens: 40,
    },
    ToolMeta {
        name: "github_get_pr",
        description: "Get details of a specific pull request",
        triggers: &[
            "pr details",
            "pull request details",
            "pr #",
            "review pr",
            "pr review",
            "merge status",
            "conflicts",
            "pr详情",
            "看看pr",
            "PR状态",
            "合并状态",
            "审查PR",
        ],
        pinned: false,
        intents: &[IntentType::GitHub],
        scope: Scope::External,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "github_ci_status",
        description: "Get CI/CD pipeline status for a branch or PR",
        triggers: &[
            "ci status",
            "pipeline",
            "build status",
            "checks",
            "actions",
            "workflow",
            "ci/cd",
            "github ci",
            "workflow status",
            "build running",
            "CI状态",
            "构建状态",
            "流水线",
            "工作流状态",
            "构建中吗",
        ],
        pinned: false,
        intents: &[IntentType::GitHub],
        scope: Scope::External,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "github_repo_stats",
        description: "Get GitHub repository stars, forks, issues, and metadata",
        triggers: &[
            "stars",
            "star",
            "forks",
            "watchers",
            "repo stats",
            "repository stats",
            "project overview",
            "overview",
            "多少star",
            "仓库数据",
            "项目概览",
            "项目数据",
        ],
        pinned: false,
        intents: &[IntentType::GitHub],
        scope: Scope::External,
        schema_tokens: 35,
    },
    ToolMeta {
        name: "github_list_issues",
        description: "List issues for a GitHub repository",
        triggers: &[
            "issues",
            "bugs",
            "list issues",
            "open issues",
            "bug list",
            "issue list",
            "问题列表",
            "最新的issue",
            "问题",
            "缺陷",
        ],
        pinned: false,
        intents: &[IntentType::GitHub],
        scope: Scope::External,
        schema_tokens: 40,
    },
    ToolMeta {
        name: "github_get_issue",
        description: "Get details of a specific issue",
        triggers: &[
            "issue details",
            "issue #",
            "bug details",
            "specific issue",
            "issue status",
            "show issue",
            "issue详情",
            "问题详情",
            "查看issue",
        ],
        pinned: false,
        intents: &[IntentType::GitHub],
        scope: Scope::External,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "github_create_issue",
        description: "Create a new issue in a GitHub repository",
        triggers: &[
            "create issue",
            "new issue",
            "file bug",
            "report issue",
            "open issue",
            "submit issue",
            "创建issue",
            "新建issue",
            "提issue",
            "提交问题",
            "创建问题",
            "报告bug",
            "新建bug",
        ],
        pinned: false,
        intents: &[IntentType::GitHub],
        scope: Scope::External,
        schema_tokens: 40,
    },
    ToolMeta {
        name: "web_fetch",
        description: "Fetch URL content — web pages, APIs, documentation",
        triggers: &[
            "fetch",
            "url",
            "web",
            "http",
            "download",
            "api call",
            "web page",
            "read url",
            "curl",
            "link",
            "open url",
            "get webpage",
            "网页",
            "网址",
            "获取网页",
            "访问链接",
            "链接",
            "打开链接",
            "获取页面",
            "打开网址",
        ],
        pinned: false,
        intents: &[IntentType::CodeRead],
        scope: Scope::External,
        schema_tokens: 25,
    },
    // Memory tools are pinned because the system prompt always includes memory rules
    // ("STORE to memory_store when user states a preference…"). If the prompt tells the
    // LLM to use a tool, that tool must be available — otherwise the LLM describes the
    // action in text instead of calling it. Cost: +65 tokens/turn (negligible).
    ToolMeta {
        name: "memory_store",
        description: "Store information to persistent memory",
        triggers: &[
            "remember",
            "store",
            "save to memory",
            "memorize",
            "note",
            "keep in mind",
            "persist",
            "archive",
            "关注",
            "follow",
            "watch",
            "track",
            "subscribe",
            "bookmark",
            "记住",
            "保存记忆",
            "存储",
            "记下",
            "记录",
            "保存",
            // Disambiguate from write_file "保存"
            "保存到记忆",
            "存储到记忆",
            "存一下",
            "帮我记住",
        ],
        pinned: true,
        intents: &[IntentType::Memory],
        scope: Scope::CrossSession,
        schema_tokens: 35,
    },
    ToolMeta {
        name: "memory_search",
        description: "Search persistent memories for relevant information",
        triggers: &[
            "recall",
            "search memory",
            "what did I",
            "memories",
            "my memory",
            "do I have",
            "what do I",
            "stored",
            "what did I say",
            "记忆",
            "回忆",
            "搜索记忆",
            "记住了什么",
            "偏好",
            "哪些记忆",
            "之前说过",
            "搜一下记忆",
        ],
        pinned: true,
        intents: &[IntentType::Memory],
        scope: Scope::CrossSession,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "memory_purge",
        description: "Delete memories by query or ID",
        triggers: &[
            "forget",
            "delete memory",
            "purge",
            "remove memory",
            "clear memory",
            "erase",
            "删除记忆",
            "忘记",
            "清除记忆",
        ],
        pinned: false,
        intents: &[IntentType::Memory],
        scope: Scope::CrossSession,
        schema_tokens: 25,
    },
    ToolMeta {
        name: "memory_correct",
        description: "Correct or update an existing memory entry",
        triggers: &[
            "correct memory",
            "update memory",
            "fix memory",
            "amend memory",
            "revise memory",
            "修正记忆",
            "更新记忆",
            "纠正记忆",
            "改记忆",
        ],
        pinned: false,
        intents: &[IntentType::Memory],
        scope: Scope::CrossSession,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "memory_profile",
        description: "Retrieve user profile and preferences from memory",
        triggers: &[
            "my preferences",
            "my profile",
            "user profile",
            "what do you know about me",
            "my settings",
            "my info",
            "用户偏好",
            "用户资料",
            "使用习惯",
            "用户配置",
            "个人信息",
        ],
        pinned: false,
        intents: &[IntentType::Memory],
        scope: Scope::CrossSession,
        schema_tokens: 20,
    },
    ToolMeta {
        name: "get_agent_info",
        description: "Get information about the agent's capabilities and state",
        triggers: &[
            "capabilities",
            "what can you do",
            "agent info",
            "tools available",
            "help",
            "how to use",
            "能做什么",
            "功能",
            "帮助",
            "代理能力",
            "代理功能",
            "怎么用",
        ],
        pinned: false,
        intents: &[IntentType::Introspect],
        scope: Scope::Local,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "reflect",
        description: "Investigate agent behavior, tool selection, and decision quality",
        triggers: &[
            "reflect",
            "why",
            "investigate",
            "debug agent",
            "what went wrong",
            "self-check",
            "diagnose",
            "trace",
            "analyze behavior",
            "what happened",
            "反思",
            "为什么",
            "调查",
            "哪里出错",
            "自检",
            "诊断",
            "排查",
            "怎么回事",
            "问题在哪",
        ],
        pinned: false,
        intents: &[IntentType::Introspect],
        scope: Scope::Local,
        schema_tokens: 40,
    },
    // ── MatrixOne tools ─────────────────────────────────────────────
    ToolMeta {
        name: "mo_query",
        description: "Execute SQL query against MatrixOne database for data exploration and analytics",
        triggers: &[
            "sql query",
            "database query",
            "database",
            "matrixone",
            "select from",
            "table",
            "schema",
            "data analytics",
            "aggregate",
            "count rows",
            "statistics",
            "report",
            "数据库",
            "查询数据",
            "表结构",
            "SQL查询",
            "数据分析",
            "统计",
            "聚合",
            "汇总",
        ],
        pinned: false,
        intents: &[IntentType::Database],
        scope: Scope::External,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "mo_snapshot",
        description: "Manage MatrixOne data snapshots for point-in-time recovery and experiments",
        triggers: &[
            "snapshot",
            "checkpoint",
            "data checkpoint",
            "save state",
            "restore",
            "rollback",
            "backup",
            "time travel",
            "快照",
            "数据快照",
            "备份",
            "回滚",
            "恢复",
        ],
        pinned: false,
        intents: &[IntentType::Database],
        scope: Scope::External,
        schema_tokens: 30,
    },
    ToolMeta {
        name: "mo_branch",
        description: "Coordinate git branches with MatrixOne data branches for experiment isolation",
        triggers: &[
            "data branch",
            "database branch",
            "experiment",
            "isolate data",
            "sync branch",
            "branch data",
            "experiment branch",
            "数据分支",
            "实验分支",
            "分支数据",
            "隔离",
        ],
        pinned: false,
        intents: &[IntentType::Database, IntentType::Git],
        scope: Scope::External,
        schema_tokens: 30,
    },
    // ── Tool Chain (multi-step composition) ──────────────────────────
    ToolMeta {
        name: "run_chain",
        description: "Execute a multi-step tool chain with variable passing between steps",
        triggers: &[
            "chain",
            "tool chain",
            "multi-step",
            "run workflow",
            "sequence",
            "compose tools",
            "step by step",
            "orchestrate",
            "batch tools",
            "链式",
            "多步",
            "编排工具",
            "编排",
            "组合工具",
            "顺序执行",
        ],
        pinned: false,
        intents: &[IntentType::CodeEdit, IntentType::CodeRead],
        scope: Scope::Local,
        schema_tokens: 80,
    },
];
