//! Contract tests for the `ToolSurface` API.
//!
//! These tests pin the current deterministic pinned/deferred model. See
//! `plans/tool-surface-deferred-simplification-2026-06-23.md`.
//!
//! Contracts under test:
//!   1. Default T1 (pinned) members are a configurable set — not the
//!      whole TOOL_CATALOG.
//!   2. User config can add, remove, or replace the default pinned set.
//!   3. Every non-T1 tool appears in the deferred list as `name + short_desc`
//!      (no schema, no parameters).
//!   4. `tools[]` bytes are stable across two successive builds with the
//!      same inputs — the Anthropic prompt-cache invariant.
//!   5. Registering a plugin does not perturb `tools[]` bytes; the new
//!      plugin appears only in the deferred manifest.
//!   6. `cache_control` lands on the last pinned tool schema.

#![cfg(test)]

use crate::tool_registry::surface::{DeferredEntry, ToolSurface, default_pinned_names};
use astra_config::ToolSurfaceConfig;
use astra_turn_core::tool::schema::tool_schema_name;
use astra_turn_core::tool_registry_meta::TOOL_CATALOG;
use serde_json::{Value, json};

// ── Fixtures ────────────────────────────────────────────────────────────────

/// Build the canonical schema pool used by the runtime surface tests.
///
/// `astra_tools::schemas::all_tool_schemas()` is the production source for
/// built-in tool schemas. `skill` is generated by the runtime skill subsystem
/// and injected into the registry, so it is the only explicit addition here.
fn catalog_schemas() -> Vec<Value> {
    let mut schemas = astra_tools::schemas::all_tool_schemas();
    schemas.push(crate::turn::skill_tool::skill_tool_schema_v2());
    schemas
}

fn plugin_schema(name: &str, description: &str) -> Value {
    json!({
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": {"type": "object", "properties": {}}
        }
    })
}

fn names(schemas: &[Value]) -> Vec<String> {
    schemas
        .iter()
        .filter_map(|s| tool_schema_name(s).map(String::from))
        .collect()
}

// ── 1. Defaults ─────────────────────────────────────────────────────────────

#[test]
fn every_default_pin_has_a_schema_in_the_canonical_pool() {
    let schema_names: std::collections::HashSet<String> =
        names(&catalog_schemas()).into_iter().collect();

    for pinned in default_pinned_names() {
        assert!(
            schema_names.contains(*pinned),
            "default pinned identity contains {pinned}, but the canonical schema pool has no schema for it"
        );
    }
}

#[test]
fn catalog_pinned_metadata_matches_runtime_default_surface_for_catalog_tools() {
    let default_pinned: std::collections::HashSet<&str> =
        default_pinned_names().iter().copied().collect();
    let catalog_default_pinned: std::collections::BTreeSet<&str> = TOOL_CATALOG
        .iter()
        .filter(|tool| default_pinned.contains(tool.name))
        .map(|tool| tool.name)
        .collect();
    let catalog_metadata_pinned: std::collections::BTreeSet<&str> = TOOL_CATALOG
        .iter()
        .filter(|tool| tool.pinned)
        .map(|tool| tool.name)
        .collect();

    assert_eq!(
        catalog_metadata_pinned, catalog_default_pinned,
        "catalog pinned metadata must not drift from runtime default pinned identities for catalog-backed tools"
    );
}

/// The default pinned set is the 13-member core.
/// See `tool_registry::identity` for the per-tool classification.
#[test]
fn pinned_default_members_are_the_core_set() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let pinned_names = names(&surface.pinned_schemas());
    let expected: std::collections::HashSet<&str> = [
        "ask_user", // structured clarification; interaction mode filters when unavailable
        "bash",
        "read_file",
        "write_file",
        "str_replace", // astra's editor tool
        "git",         // VCS observability is part of the coding loop
        "grep",
        "glob",
        "list_dir",
        "memory", // intrinsic per TOOL_CATALOG comment
        "tool_search",
        "skill",
        "task", // session_todos surface — TUI dashboard depends on it
    ]
    .into_iter()
    .collect();

    for must_have in &expected {
        assert!(
            pinned_names.iter().any(|n| n == must_have),
            "default pinned must contain {must_have}; got {pinned_names:?}"
        );
    }
    assert_eq!(
        pinned_names.len(),
        expected.len(),
        "exactly {} default pinned, got {}: {pinned_names:?}",
        expected.len(),
        pinned_names.len()
    );
    assert!(
        !pinned_names.iter().any(|n| n == "introspect"),
        "introspect is diagnostic-only and must remain deferred by default"
    );
}

#[test]
fn pinned_schemas_are_sorted_alphabetically_for_cache_stability() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let names = names(&surface.pinned_schemas());
    let mut sorted = names.clone();
    sorted.sort();
    assert_eq!(names, sorted, "pinned must be sorted alphabetically");
}

// ── 2. Config overrides ─────────────────────────────────────────────────────

#[test]
fn config_pinned_tools_additive_appends_to_defaults() {
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec!["github".into(), "memory".into()],
    };
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let pinned = names(&surface.pinned_schemas());
    assert!(pinned.iter().any(|n| n == "github"));
    assert!(pinned.iter().any(|n| n == "memory"));
    // Defaults still there
    assert!(pinned.iter().any(|n| n == "bash"));
    assert!(pinned.iter().any(|n| n == "tool_search"));
}

#[test]
fn config_pinned_tools_prefix_dash_removes_default() {
    // Remove grep from the default set — user prefers `bash grep` instead.
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec!["-grep".into()],
    };
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let pinned = names(&surface.pinned_schemas());
    assert!(
        !pinned.iter().any(|n| n == "grep"),
        "-grep in config must remove grep from pinned; got {pinned:?}"
    );
    // grep now appears in deferred instead.
    assert!(
        surface.deferred().iter().any(|e| e.name == "grep"),
        "grep removed from pinned must land in deferred"
    );
}

#[test]
fn empty_and_malformed_config_entries_are_ignored_not_panic() {
    // Footguns the user might type by accident: bare "-", "--foo",
    // empty string, leading whitespace. All should be silently ignored
    // (or sanitised), not panic and not misinterpret.
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec![
            "".into(),
            "-".into(),
            "--foo".into(),
            "  ".into(),
            " github".into(),
        ],
    };
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let pinned = names(&surface.pinned_schemas());
    // `--foo` is NOT a valid "remove -foo" because -foo isn't a real tool
    // AND double-dash is not our syntax. Must be ignored, not applied.
    // ` github` (leading space) is NOT the same as `github` — must be ignored.
    assert!(!pinned.iter().any(|n| n == "foo"));
    assert!(
        !pinned.iter().any(|n| n == " github"),
        "whitespace-prefixed names must be rejected"
    );
    // Defaults survive all this malformed input.
    assert!(pinned.iter().any(|n| n == "bash"));
    assert!(pinned.iter().any(|n| n == "tool_search"));
}

#[test]
fn unknown_tool_name_in_config_is_ignored_not_panic() {
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec!["not_a_real_tool".into(), "-also_not_real".into()],
    };
    // Should not panic; unknown names simply do nothing.
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let pinned = names(&surface.pinned_schemas());
    assert!(!pinned.iter().any(|n| n == "not_a_real_tool"));
    // Defaults preserved.
    assert!(pinned.iter().any(|n| n == "bash"));
}

// ── 3. Deferred manifest ────────────────────────────────────────────────────

#[test]
fn deferred_list_contains_every_non_pinned_tool() {
    let cfg = ToolSurfaceConfig::default();
    let schemas = catalog_schemas();
    let schema_names = names(&schemas);
    let surface = ToolSurface::build(schemas, &cfg, &[]);

    let pinned: std::collections::HashSet<String> =
        names(&surface.pinned_schemas()).into_iter().collect();
    let deferred: std::collections::HashSet<String> =
        surface.deferred().iter().map(|e| e.name.clone()).collect();

    // Partition: every canonical schema is in exactly one of the two.
    for tool_name in schema_names {
        let in_pinned = pinned.contains(&tool_name);
        let in_deferred = deferred.contains(&tool_name);
        assert!(
            in_pinned ^ in_deferred,
            "{} must be in exactly one of {{pinned, deferred}}; pinned={in_pinned} deferred={in_deferred}",
            tool_name
        );
    }
}

#[test]
fn deferred_catalog_stays_stable_when_catalog_tools_are_visible() {
    let cfg = ToolSurfaceConfig::default();
    let visible = std::collections::HashSet::from([
        "enter_plan_mode".to_string(),
        "exit_plan_mode".to_string(),
    ]);

    let surface = ToolSurface::build_excluding_visible(catalog_schemas(), &cfg, &[], &visible);
    let deferred: std::collections::HashSet<String> = surface
        .deferred()
        .iter()
        .map(|entry| entry.name.clone())
        .collect();

    // Deferred set is STABLE per session — visible tools MAY also appear
    // in deferred. The system prompt instructs the model to prefer tools[]
    // over <deferred_tools>. This test now verifies the deferred set is
    // non-empty and self-consistent (no duplicates, no pinned tools in deferred).
    assert!(
        !deferred.is_empty(),
        "deferred set should be non-empty even when some tools are visible"
    );
    let pinned_from_config: std::collections::HashSet<String> =
        cfg.pinned_tools.iter().cloned().collect();
    assert!(
        deferred.is_disjoint(&pinned_from_config),
        "pinned tools must never appear in deferred; pinned={pinned_from_config:?} deferred={deferred:?}"
    );
}

#[test]
fn visible_plugin_is_filtered_even_when_mixed_into_catalog_pool() {
    let cfg = ToolSurfaceConfig::default();
    let plugin = plugin_schema("mcp__weather", "Get weather for a city.");
    let mut mixed_catalog = catalog_schemas();
    mixed_catalog.push(plugin.clone());
    let visible = std::collections::HashSet::from(["mcp__weather".to_string()]);

    let surface = ToolSurface::build_excluding_visible(mixed_catalog, &cfg, &[plugin], &visible);

    assert!(
        !surface
            .deferred()
            .iter()
            .any(|entry| entry.name == "mcp__weather"),
        "visible plugin schemas must not also remain activatable in deferred"
    );
}

#[test]
fn non_visible_plugin_is_deferred_once_when_mixed_into_catalog_pool() {
    let cfg = ToolSurfaceConfig::default();
    let plugin = plugin_schema("mcp__weather", "Get weather for a city.");
    let mut mixed_catalog = catalog_schemas();
    mixed_catalog.push(plugin.clone());
    let visible = std::collections::HashSet::new();

    let surface = ToolSurface::build_excluding_visible(mixed_catalog, &cfg, &[plugin], &visible);
    let count = surface
        .deferred()
        .iter()
        .filter(|entry| entry.name == "mcp__weather")
        .count();

    assert_eq!(
        count, 1,
        "plugin schemas should be represented by the dynamic plugin pool, not duplicated through mixed catalog input"
    );
}

#[test]
fn deferred_manifest_is_atomic_text_budget_and_names() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let manifest = surface
        .deferred_manifest(Some("gpt-4o"))
        .expect("default surface should have deferred tools");

    assert!(manifest.text.contains("<deferred_tools>"));
    assert_eq!(
        manifest.context_window,
        crate::prompts::budget_for_model(Some("gpt-4o")).model_limit
    );
    assert_eq!(
        manifest.names,
        surface
            .deferred()
            .iter()
            .map(|entry| entry.name.clone())
            .collect::<Vec<_>>(),
        "producer must expose the exact names rendered in the deferred prompt block"
    );
}

#[test]
fn deferred_manifest_names_follow_rendered_budget_subset() {
    let cfg = ToolSurfaceConfig::default();
    let schemas: Vec<Value> = (0..200)
        .map(|idx| {
            json!({
                "type": "function",
                "function": {
                    "name": format!("tool_{idx:03}"),
                    "description": "A deliberately verbose deferred tool description that makes the rendered listing hit the small-model budget quickly.",
                    "parameters": {"type": "object", "properties": {}}
                }
            })
        })
        .collect();
    let surface = ToolSurface::build(schemas, &cfg, &[]);

    let manifest = surface
        .deferred_manifest(Some("gpt-3.5-turbo"))
        .expect("large deferred surface should render a budgeted subset");
    let all_deferred_names: Vec<String> = surface
        .deferred()
        .iter()
        .map(|entry| entry.name.clone())
        .collect();

    assert!(
        manifest.names.len() < all_deferred_names.len(),
        "test requires budget omission; rendered={} total={}",
        manifest.names.len(),
        all_deferred_names.len()
    );
    for name in &manifest.names {
        assert!(
            manifest.text.contains(&format!("<name>{name}</name>")),
            "manifest exposed {name}, but the prompt block did not render that name: {}",
            manifest.text
        );
    }
    let omitted = all_deferred_names
        .iter()
        .find(|name| !manifest.names.contains(name))
        .expect("budgeted manifest should omit at least one name");
    assert!(
        !manifest.text.contains(&format!("<name>{omitted}</name>")),
        "test setup expected {omitted} to be omitted from rendered prompt"
    );
}

#[test]
fn custom_type_is_rejected_while_missing_type_function_shorthand_can_be_pinned() {
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec!["missing_type".to_string(), "custom_shape".to_string()],
    };
    let surface = ToolSurface::build(
        vec![
            plugin_schema("valid_tool", "A valid deferred tool."),
            json!({"function": {"name": "missing_type", "description": "bad"}}),
            json!({"type": "custom", "function": {"name": "custom_shape", "description": "bad"}}),
        ],
        &cfg,
        &[],
    );

    assert!(names(&surface.pinned_schemas()).contains(&"missing_type".to_string()));
    assert!(!names(&surface.pinned_schemas()).contains(&"custom_shape".to_string()));
    assert_eq!(
        surface
            .deferred()
            .iter()
            .map(|entry| entry.name.as_str())
            .collect::<Vec<_>>(),
        vec!["valid_tool"]
    );
}

#[test]
fn deferred_manifest_exists_when_every_tool_is_visible() {
    let cfg = ToolSurfaceConfig::default();
    let visible: std::collections::HashSet<String> = catalog_schemas()
        .iter()
        .filter_map(|schema| {
            schema
                .get("function")
                .and_then(|function| function.get("name"))
                .and_then(serde_json::Value::as_str)
                .map(ToString::to_string)
        })
        .collect();
    let surface = ToolSurface::build_excluding_visible(catalog_schemas(), &cfg, &[], &visible);

    // Deferred set is STABLE per session — it persists even when every tool
    // is marked visible. The system prompt's <deferred_tools> block must
    // remain byte-stable (CacheScope::Session) regardless of tool surface includes.
    assert!(
        !surface.deferred().is_empty(),
        "deferred set must persist even when all tools are referenced as visible"
    );
    assert!(
        surface.deferred_manifest(Some("gpt-4o")).is_some(),
        "callers must still get names/activatable state from the persisted deferred manifest"
    );
}

#[test]
fn deferred_entries_are_name_plus_short_desc_capped() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    for entry in surface.deferred() {
        assert!(!entry.name.is_empty(), "deferred entry must have a name");
        assert!(
            entry.short_desc.chars().count() <= 180,
            "short_desc for {} exceeds 180 chars: {} chars",
            entry.name,
            entry.short_desc.chars().count()
        );
    }
}

#[test]
fn deferred_agent_summaries_keep_load_bearing_constraints() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let deferred = surface
        .deferred()
        .iter()
        .map(|entry| (entry.name.as_str(), entry.short_desc.as_str()))
        .collect::<std::collections::HashMap<_, _>>();

    let agent = deferred
        .get("agent")
        .expect("agent should be deferred by default");
    assert!(
        agent.contains("description+prompt")
            && agent.contains("agent_id")
            && agent.contains("foreground")
            && agent.contains("run_chain"),
        "agent deferred summary must keep spawn/get_result/run_chain constraints: {agent}"
    );

    let fanout = deferred
        .get("agent_fanout")
        .expect("agent_fanout should be deferred by default");
    assert!(
        fanout.contains("exactly target_count slots")
            && fanout.contains("description+prompt")
            && fanout.contains("no brief/agents/background"),
        "agent_fanout deferred summary must keep count and slot-shape constraints: {fanout}"
    );
}

#[test]
fn deferred_entries_have_no_schema_or_parameters() {
    // Structural test: DeferredEntry is name + short_desc only. Serializing
    // it must not include a `parameters` field. This guards against drift
    // where someone adds schema to the entry and bloats the prompt.
    let entry = DeferredEntry {
        name: "x".into(),
        short_desc: "y".into(),
    };
    let as_json = serde_json::to_value(&entry).expect("serializable");
    assert!(
        as_json.get("parameters").is_none(),
        "DeferredEntry must not carry parameters; got {as_json}"
    );
}

#[test]
fn deferred_list_is_sorted_alphabetically() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let names: Vec<&str> = surface.deferred().iter().map(|e| e.name.as_str()).collect();
    let mut sorted = names.clone();
    sorted.sort();
    assert_eq!(
        names, sorted,
        "deferred list must be sorted for cache stability"
    );
}

// ── 4. Byte stability (cache invariant) ─────────────────────────────────────

#[test]
fn tools_array_is_byte_stable_across_two_builds() {
    let cfg = ToolSurfaceConfig::default();
    let a = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let b = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let bytes_a = serde_json::to_vec(&a.pinned_schemas()).expect("json");
    let bytes_b = serde_json::to_vec(&b.pinned_schemas()).expect("json");
    assert_eq!(bytes_a, bytes_b, "pinned tools[] must be byte-stable");
}

#[test]
fn tools_array_byte_stable_when_plugin_registered_as_deferred() {
    let cfg = ToolSurfaceConfig::default();
    let baseline = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let plugin = vec![plugin_schema("mcp__weather", "Get weather for a city")];
    let with_plugin = ToolSurface::build(catalog_schemas(), &cfg, &plugin);

    let bytes_baseline = serde_json::to_vec(&baseline.pinned_schemas()).expect("json");
    let bytes_with = serde_json::to_vec(&with_plugin.pinned_schemas()).expect("json");
    assert_eq!(
        bytes_baseline, bytes_with,
        "registering a plugin must NOT perturb pinned tools[] bytes — plugin goes to deferred"
    );
    assert!(
        with_plugin
            .deferred()
            .iter()
            .any(|e| e.name == "mcp__weather"),
        "plugin must appear in deferred list"
    );
}

#[test]
fn plugin_is_not_auto_pinned() {
    // Corollary of the previous test: plugins default to deferred even if
    // they'd fit in the pinned budget. User must opt-in via config.
    let cfg = ToolSurfaceConfig::default();
    let plugin = vec![plugin_schema("mcp__db", "Query the internal DB")];
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &plugin);
    assert!(
        !names(&surface.pinned_schemas())
            .iter()
            .any(|n| n == "mcp__db"),
        "plugin must NOT be auto-pinned"
    );
}

#[test]
fn deferred_entries_are_sorted_alphabetically() {
    // BTreeMap iteration guarantees alphabetical order during build,
    // but asserting this confirms it doesn't regress.
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let deferred_names: Vec<&str> = surface
        .deferred()
        .iter()
        .map(|entry| entry.name.as_str())
        .collect();
    let mut sorted = deferred_names.clone();
    sorted.sort();
    assert_eq!(
        deferred_names, sorted,
        "deferred entries must be sorted alphabetically for cache stability"
    );
}

#[test]
fn pinned_schemas_are_sorted_alphabetically() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let pinned_names = names(&surface.pinned_schemas());
    let mut sorted: Vec<String> = pinned_names.clone().into_iter().collect();
    sorted.sort();
    assert_eq!(
        Vec::from_iter(pinned_names),
        sorted,
        "pinned schemas must be sorted alphabetically for cache stability"
    );
}

// ── 5. cache_control placement ──────────────────────────────────────────────

#[test]
fn cache_control_sits_on_last_pinned_tool_schema() {
    use crate::turn::prompt_cache::{
        PromptCacheConfig, annotate_tool_schemas_for_caching_with_pinned,
    };
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let mut tools = surface.pinned_schemas();
    let pinned_names = surface.pinned_names().into_iter().collect();
    let cache_cfg = PromptCacheConfig {
        cache_enabled: true,
        is_anthropic: true,
    };
    annotate_tool_schemas_for_caching_with_pinned(&mut tools, &cache_cfg, &pinned_names);

    let last = tools.last().expect("non-empty");
    assert!(
        last.get("cache_control").is_some(),
        "last pinned tool must carry cache_control; got {}",
        serde_json::to_string(last).unwrap()
    );
    // And no other tool should.
    for t in &tools[..tools.len() - 1] {
        assert!(
            t.get("cache_control").is_none(),
            "only the last pinned tool should carry cache_control"
        );
    }
}
