//! Contract tests for the `ToolSurface` API.
//!
//! These tests specify the current deterministic always_load/deferred model. See
//! `plans/tool-surface-deferred-simplification-2026-06-23.md`.
//!
//! Contracts under test:
//!   1. Default T1 (always_load) candidate members come from
//!      `ToolSpec.load_policy`; final visibility is provider/binding gated.
//!   2. User config can add extra tools to the default always_load set.
//!   3. Every non-T1 tool appears in the deferred list as `name + short_desc`
//!      (no schema, no parameters).
//!   4. `tools[]` bytes are stable across two successive builds with the
//!      same inputs — the Anthropic prompt-cache invariant.
//!   5. Registering a plugin does not perturb `tools[]` bytes; the new
//!      plugin appears only in the deferred manifest.
//!   6. `cache_control` lands on the last always_load tool schema.

#![cfg(test)]

use crate::tool_registry::surface::{
    DeferredEntry, ToolSurface, default_always_load_names, missing_always_load_schema_names,
};
use astra_config::ToolSurfaceConfig;
use astra_turn_core::tool::schema::tool_schema_name;
use serde_json::{Value, json};

// ── Fixtures ────────────────────────────────────────────────────────────────

/// Build the canonical schema pool used by the runtime surface tests.
///
/// `astra_tools::schemas::all_tool_schemas()` is the production source for
/// built-in tool schemas. `skill` is generated by the runtime skill subsystem
/// and injected into the registry, so it is the only explicit addition here.
fn catalog_schemas() -> Vec<Value> {
    let mut schemas = astra_tools::schemas::all_tool_schemas();
    schemas.push(crate::turn::skill_tool::skill_tool_schema_v2());
    schemas
}

fn plugin_schema(name: &str, description: &str) -> Value {
    json!({
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": {"type": "object", "properties": {}}
        }
    })
}

fn names(schemas: &[Value]) -> Vec<String> {
    schemas
        .iter()
        .filter_map(|s| tool_schema_name(s).map(String::from))
        .collect()
}

fn schema_name_set() -> std::collections::BTreeSet<String> {
    names(&catalog_schemas()).into_iter().collect()
}

// ── 1. Defaults ─────────────────────────────────────────────────────────────

#[test]
fn every_default_always_load_has_a_schema_in_the_canonical_pool() {
    let missing = missing_always_load_schema_names(default_always_load_names());
    assert!(
        missing.is_empty(),
        "default always_load ToolSpec contains tools missing from the canonical schema pool: {missing:?}"
    );
}

#[test]
fn public_schema_names_have_public_runtime_tool_specs() {
    let registry = astra_runtime_env::ToolRegistry::builtins();

    for name in schema_name_set() {
        let spec = registry
            .get(&name)
            .unwrap_or_else(|| panic!("schema tool has no runtime ToolSpec: {name}"));
        assert!(
            spec.load_policy.is_public_schema_policy(),
            "schema tool must not be internal: {name}"
        );
    }
}

#[test]
fn internal_runtime_tool_specs_do_not_have_public_schemas() {
    let schema_names = schema_name_set();
    let registry = astra_runtime_env::ToolRegistry::builtins();

    for spec in registry
        .iter()
        .filter(|spec| spec.load_policy == astra_runtime_env::ToolLoadPolicy::Internal)
    {
        assert!(
            !schema_names.contains(&spec.name),
            "internal runtime ToolSpec must not have a public schema: {}",
            spec.name
        );
    }
}

#[test]
fn surface_build_rejects_internal_builtin_schemas_from_any_pool() {
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec!["delete_file".to_string(), "missing_type".to_string()],
    };
    let surface = ToolSurface::build(
        vec![
            plugin_schema("delete_file", "Internal delete implementation detail."),
            json!({"function": {"name": "missing_type", "description": "dynamic public tool"}}),
        ],
        &cfg,
        &[plugin_schema(
            "multi_edit",
            "Internal multi-edit implementation detail.",
        )],
    );

    let always_load = names(&surface.always_load_schemas());
    let deferred: std::collections::BTreeSet<&str> = surface
        .deferred()
        .iter()
        .map(|entry| entry.name.as_str())
        .collect();

    assert!(
        !always_load.iter().any(|name| name == "delete_file"),
        "internal builtin must not be promoted by config"
    );
    assert!(
        !deferred.contains("delete_file") && !deferred.contains("multi_edit"),
        "internal builtins must not appear in deferred discovery"
    );
    assert!(
        always_load.iter().any(|name| name == "missing_type"),
        "non-builtin dynamic schemas remain eligible for explicit always_load config"
    );
}

#[test]
fn server_builtin_inventory_is_public_schema_backed() {
    let schema_names = schema_name_set();
    let registry = astra_runtime_env::ToolRegistry::builtins();

    for &name in crate::provider::server_builtin::SERVER_BUILTIN_TOOL_NAMES {
        let spec = registry
            .get(name)
            .unwrap_or_else(|| panic!("server builtin inventory has no ToolSpec: {name}"));
        assert!(
            spec.load_policy.is_public_schema_policy(),
            "server builtin inventory must not expose internal runtime tool: {name}"
        );
        assert!(
            schema_names.contains(name),
            "server builtin inventory must be schema-backed: {name}"
        );
    }
}

/// The declaration-level default always_load set follows ToolSpec load policy.
/// It is intentionally not the final per-access-mode visible surface.
#[test]
fn always_load_default_candidates_follow_tool_spec_load_policy() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let always_load_names: std::collections::BTreeSet<String> =
        names(&surface.always_load_schemas()).into_iter().collect();
    let expected: std::collections::BTreeSet<String> = astra_runtime_env::ToolRegistry::builtins()
        .iter()
        .filter(|spec| spec.load_policy == astra_runtime_env::ToolLoadPolicy::AlwaysLoad)
        .map(|spec| spec.name.clone())
        .collect();

    assert_eq!(
        always_load_names, expected,
        "default always_load candidates must come from ToolSpec.load_policy"
    );
}

#[test]
fn web_no_workspace_final_surface_filters_workspace_executor_candidates() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let candidate_names: std::collections::BTreeSet<String> =
        names(&surface.always_load_schemas()).into_iter().collect();

    for candidate in ["bash", "read_file", "write_file", "git"] {
        assert!(
            candidate_names.contains(candidate),
            "{candidate} remains a declaration-level T1 candidate"
        );
    }

    let filtered =
        crate::server::tool_binding_projection::capability_filter_tool_schemas_for_binding(
            surface.always_load_schemas(),
            &crate::server::tool_execution_binding::WorkspaceBinding {
                kind: astra_runtime_env::WorkspaceBindingKind::None,
                display_name: "No workspace".to_string(),
                cwd: None,
                authority: astra_runtime_env::WorkspaceAuthority::None,
                fallback_policy: crate::server::tool_execution_binding::FallbackPolicy::Disabled,
            },
            &crate::server::tool_execution_binding::ExecutorBinding::server_control_plane(),
            None,
        );
    let final_names: std::collections::BTreeSet<String> = names(&filtered).into_iter().collect();

    for visible in ["ask_user", "tool_search", "introspect", "reflect"] {
        assert!(
            final_names.contains(visible),
            "{visible} should remain visible in Web/no-workspace mode"
        );
    }
    for hidden in ["bash", "read_file", "write_file", "git"] {
        assert!(
            !final_names.contains(hidden),
            "{hidden} must be hidden until an execution provider binding exists"
        );
    }
}

#[test]
fn always_load_schemas_are_sorted_alphabetically_for_cache_stability() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let names = names(&surface.always_load_schemas());
    let mut sorted = names.clone();
    sorted.sort();
    assert_eq!(names, sorted, "always_load must be sorted alphabetically");
}

#[test]
fn surface_snapshot_exposes_visible_tools_and_tier_counts() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let snapshot = surface.snapshot();
    let always_load = names(&surface.always_load_schemas());

    assert_eq!(snapshot.visible_tools, always_load);
    assert_eq!(
        snapshot.tier_counts.always_load as usize,
        snapshot.visible_tools.len()
    );
    assert_eq!(snapshot.tier_counts.deferred_active, 0);
    assert_eq!(
        snapshot.tier_counts.deferred_available as usize,
        surface.deferred().len()
    );
}

// ── 2. Config additions ─────────────────────────────────────────────────────

#[test]
fn config_always_load_tools_additive_appends_to_defaults() {
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec!["github".into(), "memory".into()],
    };
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let always_load = names(&surface.always_load_schemas());
    assert!(always_load.iter().any(|n| n == "github"));
    assert!(always_load.iter().any(|n| n == "memory"));
    // Defaults still there
    assert!(always_load.iter().any(|n| n == "bash"));
    assert!(always_load.iter().any(|n| n == "tool_search"));
}

#[test]
fn config_always_load_tools_unknown_name_does_not_remove_defaults() {
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec!["not_a_real_tool".into()],
    };
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let always_load = names(&surface.always_load_schemas());
    assert!(
        always_load.iter().any(|n| n == "grep"),
        "unknown always_load_tools entries must not remove default always_load tools: {always_load:?}"
    );
    assert!(
        !surface.deferred().iter().any(|e| e.name == "grep"),
        "default always_load grep must not also land in deferred"
    );
}

#[test]
fn empty_and_malformed_config_entries_are_ignored_not_panic() {
    // Footguns the user might type by accident: empty strings, malformed
    // unknown names, and surrounding whitespace. They must not panic or change
    // defaults.
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec![
            "".into(),
            "-".into(),
            "--foo".into(),
            "  ".into(),
            " github".into(),
        ],
    };
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let always_load = names(&surface.always_load_schemas());
    assert!(!always_load.iter().any(|n| n == "foo"));
    assert!(always_load.iter().any(|n| n == "github"));
    assert!(
        !always_load.iter().any(|n| n == " github"),
        "stored tool names must stay canonical"
    );
    // Defaults survive all this malformed input.
    assert!(always_load.iter().any(|n| n == "grep"));
    assert!(always_load.iter().any(|n| n == "bash"));
    assert!(always_load.iter().any(|n| n == "tool_search"));
}

#[test]
fn unknown_tool_name_in_config_is_ignored_not_panic() {
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec!["not_a_real_tool".into(), "-also_not_real".into()],
    };
    // Should not panic; unknown names simply do nothing.
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let always_load = names(&surface.always_load_schemas());
    assert!(!always_load.iter().any(|n| n == "not_a_real_tool"));
    assert!(always_load.iter().any(|n| n == "grep"));
    // Defaults preserved.
    assert!(always_load.iter().any(|n| n == "bash"));
}

// ── 3. Deferred manifest ────────────────────────────────────────────────────

#[test]
fn deferred_list_contains_every_non_always_load_tool() {
    let cfg = ToolSurfaceConfig::default();
    let schemas = catalog_schemas();
    let schema_names = names(&schemas);
    let surface = ToolSurface::build(schemas, &cfg, &[]);

    let always_load: std::collections::HashSet<String> =
        names(&surface.always_load_schemas()).into_iter().collect();
    let deferred: std::collections::HashSet<String> =
        surface.deferred().iter().map(|e| e.name.clone()).collect();

    // Partition: every canonical schema is in exactly one of the two.
    for tool_name in schema_names {
        let in_always_load = always_load.contains(&tool_name);
        let in_deferred = deferred.contains(&tool_name);
        assert!(
            in_always_load ^ in_deferred,
            "{} must be in exactly one of {{always_load, deferred}}; always_load={in_always_load} deferred={in_deferred}",
            tool_name
        );
    }
}

#[test]
fn observation_tools_are_always_load_and_not_deferred() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let always_load: std::collections::HashSet<String> =
        names(&surface.always_load_schemas()).into_iter().collect();
    let deferred: std::collections::HashSet<String> = surface
        .deferred()
        .iter()
        .map(|entry| entry.name.clone())
        .collect();

    for tool in ["introspect", "reflect"] {
        assert!(
            always_load.contains(tool),
            "{tool} must be visible without deferred activation"
        );
        assert!(
            !deferred.contains(tool),
            "{tool} must not also appear in deferred discovery"
        );
    }

    let manifest = surface
        .deferred_manifest_with_context_window(Some(200_000))
        .expect("default surface should still have other deferred tools");
    for tool in ["introspect", "reflect"] {
        assert!(
            !manifest.names.iter().any(|name| name == tool),
            "{tool} must not be advertised as deferred"
        );
        assert!(
            !manifest.text.contains(&format!("\n{tool}\n")),
            "{tool} must not be rendered in the deferred prompt block"
        );
    }
}

#[test]
fn deferred_catalog_excludes_catalog_tools_that_are_visible() {
    let cfg = ToolSurfaceConfig::default();
    let visible = std::collections::HashSet::from([
        "enter_plan_mode".to_string(),
        "exit_plan_mode".to_string(),
    ]);

    let surface = ToolSurface::build_excluding_visible(catalog_schemas(), &cfg, &[], &visible);
    let deferred: std::collections::HashSet<String> = surface
        .deferred()
        .iter()
        .map(|entry| entry.name.clone())
        .collect();

    assert!(
        !deferred.is_empty(),
        "deferred set should be non-empty even when some tools are visible"
    );
    assert!(
        deferred.is_disjoint(&visible),
        "visible tools must not also appear in deferred; visible={visible:?} deferred={deferred:?}"
    );
}

#[test]
fn visible_plugin_is_filtered_even_when_mixed_into_catalog_pool() {
    let cfg = ToolSurfaceConfig::default();
    let plugin = plugin_schema("mcp__weather", "Get weather for a city.");
    let mut mixed_catalog = catalog_schemas();
    mixed_catalog.push(plugin.clone());
    let visible = std::collections::HashSet::from(["mcp__weather".to_string()]);

    let surface = ToolSurface::build_excluding_visible(mixed_catalog, &cfg, &[plugin], &visible);

    assert!(
        !surface
            .deferred()
            .iter()
            .any(|entry| entry.name == "mcp__weather"),
        "visible plugin schemas must not also remain activatable in deferred"
    );
}

#[test]
fn non_visible_plugin_is_deferred_once_when_mixed_into_catalog_pool() {
    let cfg = ToolSurfaceConfig::default();
    let plugin = plugin_schema("mcp__weather", "Get weather for a city.");
    let mut mixed_catalog = catalog_schemas();
    mixed_catalog.push(plugin.clone());
    let visible = std::collections::HashSet::new();

    let surface = ToolSurface::build_excluding_visible(mixed_catalog, &cfg, &[plugin], &visible);
    let count = surface
        .deferred()
        .iter()
        .filter(|entry| entry.name == "mcp__weather")
        .count();

    assert_eq!(
        count, 1,
        "plugin schemas should be represented by the dynamic plugin pool, not duplicated through mixed catalog input"
    );
}

#[test]
fn deferred_manifest_is_atomic_text_budget_and_names() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let manifest = surface
        .deferred_manifest_with_context_window(Some(200_000))
        .expect("default surface should have deferred tools");

    assert!(manifest.text.contains("<deferred-tools>"));
    assert_eq!(
        manifest.context_window,
        crate::prompts::DEFAULT_CONTEXT_WINDOW_TOKENS
    );
    assert_eq!(
        manifest.names,
        surface
            .deferred()
            .iter()
            .map(|entry| entry.name.clone())
            .collect::<Vec<_>>(),
        "producer must expose the exact names rendered in the deferred prompt block"
    );
    assert!(
        manifest.omitted_names.is_empty(),
        "full-budget manifest must not report omitted deferred tools"
    );
}

#[test]
fn deferred_manifest_names_follow_rendered_budget_subset() {
    let cfg = ToolSurfaceConfig::default();
    let schemas: Vec<Value> = (0..200)
        .map(|idx| {
            json!({
                "type": "function",
                "function": {
                    "name": format!("tool_{idx:03}"),
                    "description": "A deliberately verbose deferred tool description that makes the rendered listing hit the small-model budget quickly.",
                    "parameters": {"type": "object", "properties": {}}
                }
            })
        })
        .collect();
    let surface = ToolSurface::build(schemas, &cfg, &[]);

    let manifest = surface
        .deferred_manifest_with_context_window(Some(16_000))
        .expect("large deferred surface should render a budgeted subset");
    let all_deferred_names: Vec<String> = surface
        .deferred()
        .iter()
        .map(|entry| entry.name.clone())
        .collect();

    assert!(
        manifest.names.len() < all_deferred_names.len(),
        "test requires budget omission; rendered={} total={}",
        manifest.names.len(),
        all_deferred_names.len()
    );
    for name in &manifest.names {
        assert!(
            manifest.text.contains(&format!("\n{name}\n")),
            "manifest exposed {name}, but the prompt block did not render that name: {}",
            manifest.text
        );
    }
    let omitted = all_deferred_names
        .iter()
        .find(|name| !manifest.names.contains(name))
        .expect("budgeted manifest should omit at least one name");
    let expected_omitted: Vec<_> = all_deferred_names
        .iter()
        .filter(|name| !manifest.names.contains(name))
        .cloned()
        .collect();
    assert_eq!(
        manifest.omitted_names, expected_omitted,
        "manifest must expose every deferred tool omitted by the rendered budget"
    );
    assert!(
        !manifest.text.contains(&format!("\n{omitted}\n")),
        "test setup expected {omitted} to be omitted from rendered prompt"
    );
    assert!(
        !manifest.text.contains("<tool>")
            && !manifest.text.contains("<name>")
            && !manifest.text.contains("<description>"),
        "deferred manifest must be a pure name list, not schema-like XML: {}",
        manifest.text
    );
}

#[test]
fn custom_type_is_rejected_while_missing_type_function_shorthand_can_be_always_load() {
    let cfg = ToolSurfaceConfig {
        pinned_tools: vec!["missing_type".to_string(), "custom_shape".to_string()],
    };
    let surface = ToolSurface::build(
        vec![
            plugin_schema("valid_tool", "A valid deferred tool."),
            json!({"function": {"name": "missing_type", "description": "bad"}}),
            json!({"type": "custom", "function": {"name": "custom_shape", "description": "bad"}}),
        ],
        &cfg,
        &[],
    );

    assert!(names(&surface.always_load_schemas()).contains(&"missing_type".to_string()));
    assert!(!names(&surface.always_load_schemas()).contains(&"custom_shape".to_string()));
    assert_eq!(
        surface
            .deferred()
            .iter()
            .map(|entry| entry.name.as_str())
            .collect::<Vec<_>>(),
        vec!["valid_tool"]
    );
}

#[test]
fn deferred_manifest_is_absent_when_every_tool_is_visible() {
    let cfg = ToolSurfaceConfig::default();
    let visible: std::collections::HashSet<String> = catalog_schemas()
        .iter()
        .filter_map(|schema| {
            schema
                .get("function")
                .and_then(|function| function.get("name"))
                .and_then(serde_json::Value::as_str)
                .map(ToString::to_string)
        })
        .collect();
    let surface = ToolSurface::build_excluding_visible(catalog_schemas(), &cfg, &[], &visible);

    assert!(
        surface.deferred().is_empty(),
        "all visible tools must be removed from deferred"
    );
    assert!(
        surface
            .deferred_manifest_with_context_window(Some(200_000))
            .is_none(),
        "no deferred prompt block should be rendered when every tool is already visible"
    );
}

#[test]
fn deferred_entries_are_name_plus_short_desc_capped() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    for entry in surface.deferred() {
        assert!(!entry.name.is_empty(), "deferred entry must have a name");
        assert!(
            entry.short_desc.chars().count() <= 180,
            "short_desc for {} exceeds 180 chars: {} chars",
            entry.name,
            entry.short_desc.chars().count()
        );
    }
}

#[test]
fn deferred_agent_summaries_keep_load_bearing_constraints() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let deferred = surface
        .deferred()
        .iter()
        .map(|entry| (entry.name.as_str(), entry.short_desc.as_str()))
        .collect::<std::collections::HashMap<_, _>>();

    let agent = deferred
        .get("agent")
        .expect("agent should be deferred by default");
    assert!(
        agent.contains("description+prompt")
            && agent.contains("agent_id")
            && agent.contains("foreground")
            && agent.contains("run_chain"),
        "agent deferred summary must keep spawn/get_result/run_chain constraints: {agent}"
    );

    let fanout = deferred
        .get("agent_fanout")
        .expect("agent_fanout should be deferred by default");
    assert!(
        fanout.contains("exactly target_count slots")
            && fanout.contains("description+prompt")
            && fanout.contains("no brief/agents/background"),
        "agent_fanout deferred summary must keep count and slot-shape constraints: {fanout}"
    );
}

#[test]
fn deferred_entries_have_no_schema_or_parameters() {
    // Structural test: DeferredEntry is name + short_desc only. Serializing
    // it must not include a `parameters` field. This guards against drift
    // where someone adds schema to the entry and bloats the prompt.
    let entry = DeferredEntry {
        name: "x".into(),
        short_desc: "y".into(),
    };
    let as_json = serde_json::to_value(&entry).expect("serializable");
    assert!(
        as_json.get("parameters").is_none(),
        "DeferredEntry must not carry parameters; got {as_json}"
    );
}

#[test]
fn deferred_list_is_sorted_alphabetically() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let names: Vec<&str> = surface.deferred().iter().map(|e| e.name.as_str()).collect();
    let mut sorted = names.clone();
    sorted.sort();
    assert_eq!(
        names, sorted,
        "deferred list must be sorted for cache stability"
    );
}

// ── 4. Byte stability (cache invariant) ─────────────────────────────────────

#[test]
fn tools_array_is_byte_stable_across_two_builds() {
    let cfg = ToolSurfaceConfig::default();
    let a = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let b = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let bytes_a = serde_json::to_vec(&a.always_load_schemas()).expect("json");
    let bytes_b = serde_json::to_vec(&b.always_load_schemas()).expect("json");
    assert_eq!(bytes_a, bytes_b, "always_load tools[] must be byte-stable");
}

#[test]
fn tools_array_byte_stable_when_plugin_registered_as_deferred() {
    let cfg = ToolSurfaceConfig::default();
    let baseline = ToolSurface::build(catalog_schemas(), &cfg, &[]);

    let plugin = vec![plugin_schema("mcp__weather", "Get weather for a city")];
    let with_plugin = ToolSurface::build(catalog_schemas(), &cfg, &plugin);

    let bytes_baseline = serde_json::to_vec(&baseline.always_load_schemas()).expect("json");
    let bytes_with = serde_json::to_vec(&with_plugin.always_load_schemas()).expect("json");
    assert_eq!(
        bytes_baseline, bytes_with,
        "registering a plugin must NOT perturb always_load tools[] bytes — plugin goes to deferred"
    );
    assert!(
        with_plugin
            .deferred()
            .iter()
            .any(|e| e.name == "mcp__weather"),
        "plugin must appear in deferred list"
    );
}

#[test]
fn plugin_is_not_auto_always_load() {
    // Corollary of the previous test: plugins default to deferred even if
    // they'd fit in the always_load budget. User must opt-in via config.
    let cfg = ToolSurfaceConfig::default();
    let plugin = vec![plugin_schema("mcp__db", "Query the internal DB")];
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &plugin);
    assert!(
        !names(&surface.always_load_schemas())
            .iter()
            .any(|n| n == "mcp__db"),
        "plugin must NOT be auto-always_load"
    );
}

#[test]
fn deferred_entries_are_sorted_alphabetically() {
    // BTreeMap iteration guarantees alphabetical order during build,
    // but asserting this confirms it doesn't regress.
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let deferred_names: Vec<&str> = surface
        .deferred()
        .iter()
        .map(|entry| entry.name.as_str())
        .collect();
    let mut sorted = deferred_names.clone();
    sorted.sort();
    assert_eq!(
        deferred_names, sorted,
        "deferred entries must be sorted alphabetically for cache stability"
    );
}

#[test]
fn always_load_schemas_are_sorted_alphabetically() {
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let always_load_names = names(&surface.always_load_schemas());
    let mut sorted: Vec<String> = always_load_names.clone().into_iter().collect();
    sorted.sort();
    assert_eq!(
        Vec::from_iter(always_load_names),
        sorted,
        "always_load schemas must be sorted alphabetically for cache stability"
    );
}

// ── 5. cache_control placement ──────────────────────────────────────────────

#[test]
fn cache_control_sits_on_last_always_load_tool_schema() {
    use crate::turn::prompt_cache::{
        PromptCacheConfig, annotate_tool_schemas_for_caching_with_always_load,
    };
    let cfg = ToolSurfaceConfig::default();
    let surface = ToolSurface::build(catalog_schemas(), &cfg, &[]);
    let mut tools = surface.always_load_schemas();
    let always_load_names = surface.always_load_names().into_iter().collect();
    let cache_cfg = PromptCacheConfig {
        cache_enabled: true,
        is_anthropic: true,
    };
    annotate_tool_schemas_for_caching_with_always_load(&mut tools, &cache_cfg, &always_load_names);

    let last = tools.last().expect("non-empty");
    assert!(
        last.get("cache_control").is_some(),
        "last always_load tool must carry cache_control; got {}",
        serde_json::to_string(last).unwrap()
    );
    // And no other tool should.
    for t in &tools[..tools.len() - 1] {
        assert!(
            t.get("cache_control").is_none(),
            "only the last always_load tool should carry cache_control"
        );
    }
}
