//! Dynamic bundled skills — prompt content generated by Rust functions.
//!
//! Each skill is a function returning (manifest_yaml, instructions) so that
//! tool names, paths, and other constants are compiled-in rather than
//! hardcoded strings that drift out of sync.

mod batch;
mod debug;
mod reflect;
mod remember;
mod review;
mod skillify;
mod stuck;
mod verify;

/// Returns all dynamic skill contents as `(frontmatter_yaml + body)` strings
/// ready to be parsed by `parse_skill_md`.
pub fn all_dynamic_skills() -> Vec<String> {
    vec![
        batch::skill_content(),
        debug::skill_content(),
        reflect::skill_content(),
        review::skill_content(),
        skillify::skill_content(),
        stuck::skill_content(),
        verify::skill_content(),
        remember::skill_content(),
    ]
}
