use axum::routing::put;

use super::*;

pub(super) fn add_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route("/", get(meta_handlers::root_handler))
        .route("/health", get(meta_handlers::health_handler))
        .route("/metrics", get(meta_handlers::metrics_handler))
        .route("/auth/register", post(auth_handlers::auth_register_handler))
        .route("/auth/login", post(auth_handlers::auth_login_handler))
        .route("/auth/refresh", post(auth_handlers::auth_refresh_handler))
        .route("/auth/logout", post(auth_handlers::auth_logout_handler))
        .route("/auth/me", get(auth_handlers::auth_me_handler))
        .route(
            "/memory/store",
            post(auth_handlers::memory_proxy_store_handler),
        )
        .route(
            "/memory/retrieve",
            post(auth_handlers::memory_proxy_retrieve_handler),
        )
        .route(
            "/memory/search",
            post(auth_handlers::memory_proxy_search_handler),
        )
        .route(
            "/memory/purge",
            post(auth_handlers::memory_proxy_purge_handler),
        )
        .route(
            "/memory/expand/{memory_id}",
            get(auth_handlers::memory_proxy_expand_handler),
        )
        .route(
            "/memory/correct",
            post(auth_handlers::memory_proxy_correct_handler),
        )
        .route(
            "/memory/correct/{memory_id}",
            put(auth_handlers::memory_proxy_correct_by_id_handler),
        )
        .route(
            "/memory/feedback/{memory_id}",
            post(auth_handlers::memory_proxy_feedback_handler),
        )
        .route(
            "/memory/profile",
            get(auth_handlers::memory_proxy_profile_handler),
        )
        .route(
            "/memory/reflect",
            post(auth_handlers::memory_proxy_reflect_handler),
        )
        .route(
            "/memory/snapshots",
            get(auth_handlers::memoria_proxy_snapshots_list_handler)
                .post(auth_handlers::memoria_proxy_snapshot_create_handler),
        )
        .route(
            "/memory/snapshots/{name}/rollback",
            post(auth_handlers::memoria_proxy_snapshot_rollback_handler),
        )
        .route(
            "/memory/snapshots/{name}/diff",
            get(auth_handlers::memoria_proxy_snapshot_diff_handler),
        )
        .route(
            "/memory/branches",
            get(auth_handlers::memoria_proxy_branches_list_handler)
                .post(auth_handlers::memoria_proxy_branch_create_handler),
        )
        .route(
            "/memory/branches/{name}/checkout",
            post(auth_handlers::memoria_proxy_branch_checkout_handler),
        )
        .route(
            "/memory/branches/{name}/merge",
            post(auth_handlers::memoria_proxy_branch_merge_handler),
        )
        .route(
            "/memory/branches/{name}/diff",
            get(auth_handlers::memoria_proxy_branch_diff_handler),
        )
        .route(
            "/memory/health",
            get(auth_handlers::memoria_proxy_health_handler),
        )
        .route(
            "/memory/governance",
            post(auth_handlers::memoria_proxy_governance_handler),
        )
        .route(
            "/memory/consolidate",
            post(auth_handlers::memoria_proxy_consolidate_handler),
        )
        .route("/chat", post(chat_handlers::chat_handler))
        .route("/chat/stream", post(chat_handlers::chat_stream_handler))
        .route("/chat/turn", post(chat_handlers::chat_turn_handler))
        .route("/chat/route", post(chat_handlers::chat_route_handler))
        .route(
            "/v1/chat/completions",
            post(completions::completions_handler),
        )
        .route(
            "/tools/result",
            post(edge::edge_callback_handlers::post_tool_result_handler),
        )
        .route(
            "/approval/respond",
            post(edge::edge_callback_handlers::post_approval_respond_handler),
        )
        .route("/chat/ws", get(ws_handler::ws_chat_handler))
        .route("/edge/ws", get(edge::edge_ws_handler::edge_ws_handler))
        .route(
            "/edges/status",
            get(edge::edge_status_handler::edge_status_handler),
        )
        .route(
            "/chat/runs/{run_id}",
            get(crate::server::run::handlers::get_run_status_handler)
                .delete(crate::server::run::handlers::cancel_run_handler),
        )
        .route(
            "/chat/runs/{run_id}/projection",
            get(crate::server::run::handlers::get_run_projection_handler),
        )
        .route(
            "/chat/runs/{run_id}/stream",
            get(crate::server::run::handlers::stream_run_handler),
        )
        .route(
            "/chat/runs/{run_id}/pause",
            post(crate::server::run::handlers::pause_run_handler),
        )
        .route(
            "/chat/runs/{run_id}/resume",
            post(crate::server::run::handlers::resume_run_handler),
        )
        .route(
            "/chat/runs/{run_id}/cancel",
            post(crate::server::run::handlers::cancel_run_handler),
        )
        .route(
            "/chat/runs/{run_id}/input",
            post(crate::server::run::handlers::submit_run_input_handler),
        )
        .route(
            "/chat/runs/{run_id}/delegate",
            post(crate::server::delegation::handlers::delegate_run_handler),
        )
        .route(
            "/chat/runs/{run_id}/delegations",
            get(crate::server::delegation::handlers::list_delegations_handler),
        )
        .route(
            "/chat/runs/{run_id}/delegations/pause",
            post(crate::server::delegation::handlers::pause_delegations_handler),
        )
        .route(
            "/chat/runs/{run_id}/delegations/resume",
            post(crate::server::delegation::handlers::resume_delegations_handler),
        )
        .route(
            "/teams",
            get(crate::server::team::handlers::list_teams_handler)
                .post(crate::server::team::handlers::upsert_team_handler),
        )
        .route(
            "/teams/{name}",
            get(crate::server::team::handlers::get_team_handler)
                .delete(crate::server::team::handlers::delete_team_handler),
        )
        .route(
            "/teams/{name}/executions",
            get(crate::server::team::handlers::list_executions_handler),
        )
        .route(
            "/teams/{name}/execute",
            post(crate::server::team::handlers::execute_team_handler),
        )
        .route(
            "/teams/{name}/snapshots",
            get(crate::server::team::handlers::list_snapshots_handler)
                .post(crate::server::team::handlers::create_snapshot_handler),
        )
        .route(
            "/teams/snapshots/{id}",
            delete(crate::server::team::handlers::delete_snapshot_handler),
        )
        .route(
            "/chat/session/{session_id}/reflect",
            get(reflect_handlers::reflect_session_handler),
        )
        .route(
            "/chat/session/{session_id}/decision-trace",
            get(reflect_handlers::decision_trace_handler),
        )
        .route(
            "/api/v1/learning/health",
            get(learning_handlers::learning_health_handler),
        )
        .route(
            "/api/v1/learning/signals",
            get(learning_handlers::learning_signals_handler),
        )
        .route(
            "/api/v1/learning/stats",
            get(learning_handlers::learning_stats_handler),
        )
        .route(
            "/api/v1/learning/trigger",
            post(learning_handlers::learning_trigger_handler),
        )
        .route(
            "/api/v1/learning/feedback",
            post(reflect_handlers::learning_feedback_handler),
        )
        .route(
            "/agents/edge/heartbeat",
            post(edge::edge_callback_handlers::post_agents_edge_heartbeat_handler),
        )
        .route(
            "/agents/edge",
            post(edge::edge_callback_handlers::post_agents_edge_register_handler),
        )
}
