//! Dynamic bundled skills — prompt content generated by Rust functions.
//!
//! Each skill is a function returning (manifest_yaml, instructions) so that
//! tool names, paths, and other constants are compiled-in rather than
//! hardcoded strings that drift out of sync.

mod debug;
mod reflect;
mod remember;
mod review;
mod skillify;
mod stuck;
mod verify;

/// Returns all dynamic skill contents as `(frontmatter_yaml + body)` strings
/// ready to be parsed by `parse_skill_md`.
///
/// Parallel orchestration is owned by the native fanout surface rather than a
/// skill-layer lifecycle.
pub fn all_dynamic_skills() -> Vec<String> {
    vec![
        debug::skill_content(),
        reflect::skill_content(),
        review::skill_content(),
        skillify::skill_content(),
        stuck::skill_content(),
        verify::skill_content(),
        remember::skill_content(),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dynamic_skills_are_valid_unique_manifests() {
        let expected = [
            "debug", "reflect", "remember", "review", "skillify", "stuck", "verify",
        ]
        .into_iter()
        .map(String::from)
        .collect();
        let mut actual = std::collections::BTreeSet::new();

        for content in all_dynamic_skills() {
            let (manifest, instructions) = crate::loader::parse_skill_md(&content)
                .expect("every dynamic skill must satisfy the canonical manifest contract");
            assert!(
                actual.insert(manifest.name),
                "dynamic skill names must be unique"
            );
            assert!(
                !instructions.trim().is_empty(),
                "dynamic skill instructions must not be empty"
            );
        }

        assert_eq!(actual, expected);
    }

    #[test]
    fn review_skill_does_not_depend_on_a_removed_orchestration_action() {
        let (manifest, _) = crate::loader::parse_skill_md(&review::skill_content())
            .expect("dynamic review skill must remain a valid skill document");
        assert_eq!(
            manifest.allowed_tools,
            vec!["bash", "read_file", "write_file"]
        );
    }
}
