"""Verify list queries exclude heavy columns (embedding, context_snapshot, etc.)."""

import pytest
from sqlalchemy import text
from uuid_utils import uuid7

from api.models.agent import Event
from core.events.event_reader import EventReader, _LIST_COLUMNS


class TestListColumnsExcludesHeavy:
    """_LIST_COLUMNS must not contain embedding or other heavy blob columns."""

    _EXCLUDED = {
        "embedding",
        "context_snapshot",
        "token_usage",
        "skills_snapshot",
        "llm_params",
        "desensitized_content",
        "embedding_ref",
        "skill_result",
    }

    def test_no_embedding_in_list_columns(self):
        col_names = {c.key for c in _LIST_COLUMNS}
        assert "embedding" not in col_names

    def test_no_heavy_json_in_list_columns(self):
        col_names = {c.key for c in _LIST_COLUMNS}
        overlap = col_names & self._EXCLUDED
        assert overlap == set(), f"Heavy columns in _LIST_COLUMNS: {overlap}"

    def test_required_columns_present(self):
        col_names = {c.key for c in _LIST_COLUMNS}
        required = {
            "event_id",
            "user_id",
            "session_id",
            "agent_id",
            "event_type",
            "content",
            "created_at",
            "parent_event_id",
            "causal_chain_id",
        }
        missing = required - col_names
        assert missing == set(), f"Missing required columns: {missing}"


@pytest.fixture
def db(db_session):
    yield db_session


class TestListQueryExcludesEmbeddingDB:
    """Integration: verify actual SQL generated by ORM excludes embedding."""

    def test_get_session_events_no_embedding(self, db):
        """Insert event, query via get_session_events, verify no embedding column returned."""
        sid = str(uuid7())
        eid = str(uuid7())
        chain = str(uuid7())

        db.execute(
            text(
                "INSERT INTO agent_events "
                "(event_id, session_id, user_id, agent_id, agent_version, "
                " event_type, content, causal_chain_id, created_at) "
                "VALUES (:eid, :sid, 'test', 'system', '1.0.0', "
                " 'user_query', 'hello', :chain, NOW())"
            ),
            {"eid": eid, "sid": sid, "chain": chain},
        )
        db.commit()

        reader = EventReader(lambda: db)
        events = reader.get_session_events(sid)
        assert len(events) == 1
        assert events[0].event_id == eid
        # embedding_ref should be None (not loaded)
        assert events[0].embedding_ref is None

        db.execute(text("DELETE FROM agent_events WHERE event_id = :eid"), {"eid": eid})
        db.commit()

    def test_get_causal_chain_no_embedding(self, db):
        """Insert event, query via get_causal_chain, verify no embedding column returned."""
        sid = str(uuid7())
        eid = str(uuid7())
        chain = str(uuid7())

        db.execute(
            text(
                "INSERT INTO agent_events "
                "(event_id, session_id, user_id, agent_id, agent_version, "
                " event_type, content, causal_chain_id, created_at) "
                "VALUES (:eid, :sid, 'test', 'system', '1.0.0', "
                " 'user_query', 'hello', :chain, NOW())"
            ),
            {"eid": eid, "sid": sid, "chain": chain},
        )
        db.commit()

        reader = EventReader(lambda: db)
        events = reader.get_causal_chain(chain)
        assert len(events) == 1
        assert events[0].event_id == eid
        assert events[0].embedding_ref is None

        db.execute(text("DELETE FROM agent_events WHERE event_id = :eid"), {"eid": eid})
        db.commit()
